### ISSUE TITLE
Complete RedisEventRepository for searchs

### ISSUE THREAD

**Issue by gadogttas** [clun/ff4j#100]
If you want to store everything feature-flipper in Redis, you need an event repository as well.
##

**Comment by clun** [comment]
I agree. The Event Repositories lag a bit behind, I'm on it.

**Comment by clun** [comment]
With heavy refactoring for v2.0 there will be the both AuditTrail and FeatureUsageTracking in REDIS. We also studied to leverage on the new Jcache capabilities. 

I will close this issue as no more relevant for 2.0, feel free to reopen if the new version does not cope with what you expected. Stay tuned.
