### ISSUE TITLE
AOP @Flip(alterClass) does not work on cglib enhanced classes

### ISSUE THREAD

**Issue by razvanfromoz** [clun/ff4j#102]
i think there's a problem at least here (when the alterclass is cglib enhanced)
https://github.com/clun/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java

```
 // expected to be cglib proxy then, which is simply a specialized class
 return proxy.getClass().equals(alterClass);
```

the proxy(some enhanced class) is different from the alter class (the original class)

there's probably an issue on FeatureAutoProxy ( when @Primary bean is cglib enhanced)
in getAdvicesAndAdvisorsForBean the beanClass.getInterfaces for a cglib enhanced class do not contain the original class implemented interfaces but (o.s.aop.SpringProxy, o.s.aop.framework.Advised,o.s.cglib.proxy.Factory)
##

**Comment by clun** [comment]
You're right that's an issue. I will make this work. It's the third time i struggle with cglib beans :)

**Comment by kutzi** [comment]
I don't know if you consider you this a different issue, but we also have problems with cglib beans and 'alterBean'
I've seen that you already changed something regarding this in https://github.com/clun/ff4j/commit/929dc701fe9e33efd464bd6ce0dbe60335a5cb65#diff-d84e6180f47ed657df0dda8599d845b0
but I guess that's not complete, yet, as the change in FeatureAutoProxy is still commented out?

**Comment by kutzi** [comment]
Care to reply on my message from Jun 21?

**Comment by clun** [comment]
Hello, sorry totally forgot this exchange, let's reopened. 

There were some changes in 1.6 to simplify this Advisor once for all. (https://github.com/clun/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java) 

The **alterBean** should now be straight forward, even with cglib:
```java
Object alterbean = appCtx.getBean(alterBeanName, method.getDeclaringClass());
method.invoke(alterbean, mi.getArguments());
```

For **alterclass**, i retrieved the declaringClass which should be OK with cglib bean:
```java
// Declare class is correct even with cglib
Class<?> declaringClass = mi.getMethod().getDeclaringClass();
for (Object bean : appCtx.getBeansOfType(declaringClass).values()) {
....
}
```

Then, the target class should match :
```java
AopUtils.isJdkDynamicProxy(bean) &&  ((Advised) bean).getTargetSource().getTarget().getClass().equals(alterClazz)
```
or 
```java
AopProxyUtils.ultimateTargetClass(bean).equals(alterClazz))
```
If not match found, it's instanciate without spring
```java
mi.getMethod().invoke(ff.alterClazz().newInstance(), mi.getArguments());
```

Do you a think a CGLIB classe can failed both AopUtils.isJdkDynamicProxy(bean)  and AopProxyUtils.ultimateTargetClass(bean) ?

**Comment by kutzi** [comment]
Sorry, this is too long ago for me to remember the details, but as there are still the commented-out lines in https://github.com/clun/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAutoProxy.java,
I would at least wonder, what was supposed to happen there.

**Comment by clun** [comment]
Ok. FF4J did not work with CGLIB enhanced classes as you noticed.

My first idea was that the `FeatureAutoProxy` (scanning beans at start to proxified if relevant) did not retrieve the annotation `Flip` because of CGLIB proxy.

In reality `FeatureAutoProxy` found the bean but the problem was in the `FeatureAdvisor` itself. The ` AopProxyUtils.ultimateTargetClass(beanClass);` was the way to go but not on the AutoProxy : on the Advisor.

I create a sample here 
https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-hystrix

Hystrix create a gclib proxy but the flipped is still working.
