### ISSUE TITLE
Alter bean don't return my exception

### ISSUE THREAD

**Issue by FelipeAdorno** [clun/ff4j#103]
I have a exception for register database not found ResourceNotFoundException and I use spring @ControllerAdivice to intercept this exception, but using FF4J the throw exception is InvocationTargetException, I think is necessary a propertie to callAlterBeanMethod return the InvocationTargetException or return invocationTargetException.getCause(). It's make sense? thanks.

**Comment by clun** [comment]
I think that FF4J try to invoke the alterBeanMethod by introspection. As the alterbean is Proxified with an advice i have some issue to invoke it. Could you give some materials to help me reproduce this (and correct).

**Comment by FelipeAdorno** [comment]
@clun I show you my case:

public Order getOrderByFilter(final Long id) {
       ....
        if(isNull(order)) {
            throw new ResourceNotFoundException(emptyList());
        }
        ...
    }

The throws exception is InvocationTargetException not my exception ResourceNotFoundException.

I can solve this problem and submit a Pull Request?

**Comment by clun** [comment]
Sure ! you are more than welcome to make some Pull requests. Even is not 100% backward compatible I will write something into the release note but i understood that the signature is not changed.

I you create a PR i woull integrate quickly to 1.4.1.
