### ISSUE TITLE
Metrics console in core?

### ISSUE THREAD

**Issue by gadogttas** [clun/ff4j#111]
I was just wondering if there is a plan to include a metrics console in this core repo. I know there is an example in the ff4j-extra repo. It could be included either in ff4j-web, or perhaps as a different module to import. Basically, I'd like to see the features in ff4j-console (from the ff4j-extra repo) merged back into the core repo. There are UI issues over there that have already been fixed on the features page, for example (wrapping of strategy text is one). Anyway, not sure if this is on the roadmap or even a priority, I was just curious. Thanks!

**Comment by clun** [comment]
Yes, it will definitively be available for 1.5 with other 2 evolutions : 
- A CLI (command line interface) to toggle features through SSH in some cases
- A Spring Boot starter

Nice catch regarding the ff4j-console.  There is indeed something with the embedded servlet and the ff4j-console. The main reason is that my WAF (Woman Acceptance Factor) is decreasing - to let me work on FF4J on spare time. I asked myself how I can get a little bit of benefice of this work. One idea was to make the great ff4j-console and made it available for 20$ but in the end I let it free.

I have other ideas like : a full reference guides & samples in each storage technology or maybe a book but nobody bought books now....

**Comment by clun** [comment]
1.5 will have a basic support for metrics in embedded (table view + few filters) and will be enhance in 1.5.x (graphs).
