### ISSUE TITLE
Sentinel Redis support

### ISSUE THREAD

**Issue by matheusmessora** [clun/ff4j#112]
The ff4j-store-redis only supports default Jedis connection.

It will be interesting if we could rely on JedisSentinelPool for high-availability.
I was looking at the code, and have 2 suggestions.

1- Change RedisConnection.java to support multiple host/port. The getJedis() method should be changed to return the jedis instance in case of single host:port, or call the JedisSentinelPool#getResource() in case of multi host configuration.
Drawback: Some methods like getRedisHost and getRedisPort should be avoided by a caller if it is a sentinel configuration

2- Create a new RedisSentinelConnection.java that is only responsible for sentinels connections. The drawback is that others classes that depends on RedisConnection should be changed too. An improvement could be change the RedisConnection to an interface, and have both implementations (Sentinel and SimpleJedisConnection) inside the org.ff44j.redis package. 
Changing RedisConnection to an interface could broke some compatibility issues.

3- Create a new RedisSentinelConnection that extends the RedisConnection, like a wrapper. This should not break compatiblity.

**Comment by clun** [comment]
Solution 1 is the simplest.

The 2 methods `getRedisHost()` and `getRedisPort()` could be deprecated.

I will change the Jedis instance by a `Pool <Jedis>` to allow both `JedisPool` and `JedisSentinelPool`
