### ISSUE TITLE
auto-configuration for ff4j-web

### ISSUE THREAD

**Issue by paul58914080** [clun/ff4j#126]
As mention by @clun 

> The [Console Servlet](https://github.com/clun/ff4j/blob/master/ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleServlet.java) is a "basic" servlet and has nothing to do with Spring. I would like to create the associated bean servletRegistrationBean when the module ff4j-web is in the classpath. As far as I understand it's a good candidate.

**Comment by paul58914080** [comment]
@clun request you to please review commit [5d8d522](https://github.com/paul58914080/ff4j-spring-boot-starter-parent/commit/5d8d5228bc43e6a15de2d877fceb1716b8119a36) and let me know if this is fine. Once you validate I will integrate the same with this repository.

**Comment by clun** [comment]
I love it, I learn in the same time :) 

Heavy work in ConsoleServlet, it will be - A LOT - better in 1.6. (but did not commit yet to master)
