### ISSUE TITLE
Can't find REST API documentation

### ISSUE THREAD

**Issue by RodolpheGohard** [clun/ff4j#128]
Hello,

I would like to use the rest API ff4j exposes, but I can't find it documented anywhere.

On the homepage there's this broken link: http://cannys.ddns.net:8081/ff4j-demo/rest/index.html

and the reference pdf guide (https://github.com/clun/ff4j-extra/raw/master/ff4j-reference-guide-1.3.pdf) says this:
```
4.3 RestFul API
Sed egestas molestie elit. Mauris urna mi, scelerisque vitae, ultrices vel, euismod vel, eros. Lorem ipsum
dolor sit amet, consectetuer adipiscing elit. Pellentesque dictum felis a nisi.
4.3.1 Introduction
Sed egestas molestie elit. Mauris urna mi, scelerisque vitae, ultrices vel, euismod vel, eros. Lorem ipsum
dolor sit amet, consectetuer adipiscing elit. Pellentesque dictum felis a nisi.
4.3.2 State Diagram
Sed egestas molestie elit. Mauris urna mi, scelerisque vitae, ultrices vel, euismod vel, eros. Lorem ipsum
dolor sit amet, consectetuer adipiscing elit. Pellentesque dictum felis a nisi.
```
which is rather unhelpful at this point.

By random trial&error, I managed to find how to list features, enable and disabled. But I can't find how to create a new feature.

**Comment by clun** [comment]
You are totally right, this is not something to be proud of documentation. I'm currently working on proper documentation.

In the mean time if you can do this:
- Clone the ff4j-extra repository an look for the project ff4j-samples/ff4j-sample-web-api
- run `mvn clean jetty:run`
- access url `http://localhost:8282/webapi/swagger/#/`
![api1](https://cloud.githubusercontent.com/assets/726536/15440250/c81e5c6e-1ed4-11e6-8fac-a6f49f917706.png)

![api2](https://cloud.githubusercontent.com/assets/726536/15440265/dda328e4-1ed4-11e6-9671-905ab84929fa.png)

plz be patient, you can ask as much as you want here also

**Comment by clun** [comment]
Other elements : 

![api3](https://cloud.githubusercontent.com/assets/726536/15440391/811ade68-1ed5-11e6-9acb-7906c84475ab.png)

![api4](https://cloud.githubusercontent.com/assets/726536/15440392/811f5fc4-1ed5-11e6-8c49-84b853ff170b.png)

![api6](https://cloud.githubusercontent.com/assets/726536/15440393/8122f85a-1ed5-11e6-97dc-075ffbe58780.png)

**Comment by RodolpheGohard** [comment]
Thanks, that helped a lot. I find my way to create features with the REST API now :).

**Comment by borislopezaraoz** [comment]
hello clun
I applied the same configuration to an existing project but I get only JSON responses, not the swagger UI, any idea what is missing?
Also I didn't understand what are the random events generated in the sample and where are they saved? I don't see them in mysql DB.

**Comment by clun** [comment]
Hi,

To have the swagger UI works you need to import some html files, those files are for instance:
https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-springboot/src/main/resources/static/swagger

To run the sample just use `mvn spring-boot:run`
Then you access the swagger page with the following URL
http://localhost:8082/swagger/index.html

![b](https://cloud.githubusercontent.com/assets/726536/22142389/622a3b66-def6-11e6-94c8-6ad925f8c12b.png)

The JSON file is used in the Access URL in the webpage
