### ISSUE TITLE
FeatureStoreAuditProxy mask  the underlying Store used

### ISSUE THREAD

**Issue by adelcourt** [clun/ff4j#130]
Since ff4j 1.5,  if audit  is enabled,  the FeatureStoreAuditProxy  is used instead of InMemoryFeatureStore and FeatureStoreMongoCollection in my case.

for my use case  i need to know the type of the Store used. 
It is planned to expose the type of underlying Store or maybe i'm making something wrong?

**Comment by clun** [comment]
Hi,

You're right, the simple way to log to audit is to create a proxy with `FeatureStoreAuditProxy`. But the underlying store is not really *hidden*, you can access it through method `getTarget()`. 

I may create a new method in `FF4j` class itself. getConcreteFeatureStore`()`. This way i can still create new fancy proxies :) ... actually i have just done it. What do you think ? 1.5.1 will be released this week anyway.

```java
    public FeatureStore getConcreteFeatureStore() {
        return getConcreteFeatureStore(getFeatureStore());
    }
    
    private FeatureStore getConcreteFeatureStore(FeatureStore fs) {
        if (fs instanceof FeatureStoreAuditProxy) {
            return getConcreteFeatureStore(((FeatureStoreAuditProxy) fs).getTarget());
        } else if (fs instanceof FF4jCacheProxy) {
            return getConcreteFeatureStore(((FF4jCacheProxy) fs).getTargetFeatureStore());
        }
        return fs;
    }
```


Hi,
You're right, the simple way to log to audit is to create a proxy with `FeatureStoreAuditProxy`. But the underlying is not hidden, you can access it through method `getTarget()`.

```java
FF4jCacheProxy
```

**Comment by adelcourt** [comment]
- the getTarget() is not present in 1.5. release, waiting for the 1.5.1  to upgrade ours libray
- getConcreteFeatureStore()  seems ok for me
thx for your quickness
