### ISSUE TITLE
Logger name in FeatureAdvisor

### ISSUE THREAD

**Issue by kutzi** [clun/ff4j#131]
Not really a bug, but more a question - sorry I don't know where a more appropriate place for questions would be.

I wonder why the targetLoggers in FeatureAdvisore use the fully qualified name of the target bean class?
Use case: I want to enable logging for feature flipping, therefore I thought there would be a unique logging name for the FeatureAdvisor, so I could only put that logger on DEBUG level.
But since every feature flip uses a different logger, this is not possible.

Since the classname is again in the log message: why does the logger to be named after the class, too?

**Comment by clun** [comment]
Well good point, as the className is in the message we should simply use the FeatureAdvisor className for logger.

https://github.com/clun/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java
