### ISSUE TITLE
ff4j-spring-boot-starter would not start due to circular reference

### ISSUE THREAD

**Issue by paul58914080** [clun/ff4j#132]
With latest version of ff4j-spring-boot-starter there is an exception when you boot 

`org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'getFF4JServlet': Requested bean is currently in creation: Is there an unresolvable circular reference?`

**Comment by paul58914080** [comment]
As a workaround use the following configuration


```
import org.ff4j.FF4j;
import org.ff4j.web.embedded.ConsoleServlet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.context.embedded.ServletRegistrationBean;
import org.springframework.boot.context.web.SpringBootServletInitializer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableAutoConfiguration(exclude = {org.ff4j.spring.boot.autoconfigure.FF4JWebConfiguration.class})
public class FF4JWebConfig extends SpringBootServletInitializer {
  @Autowired
  private FF4j ff4j;

  @Bean
  public ServletRegistrationBean servletRegistrationBean() {
    return new ServletRegistrationBean(getFF4JServlet(), "/ff4j-console");
  }

  @Bean
  public ConsoleServlet getFF4JServlet() {
    ConsoleServlet ff4jServlet = new ConsoleServlet();
    ff4jServlet.setFf4j(ff4j);
    return ff4jServlet;
  }
}

```

**Comment by pclair** [comment]
Thanks for work around. Now when accessing /ff4j-console, page displays only text, no graphics (looks like issue with css or script dependency ???) not sure. Can you please provide quick help ?

**Comment by clun** [comment]
You're right. There is a new (and very cool) UI in next version. (see #118) I think i broke the old one

You can test it by defining the following Servlet (and use the version in HEAD.)

```xml
	<servlet>
		<servlet-name>ff4j-console</servlet-name>
		<servlet-class>org.ff4j.web.FF4jDispatcherServlet</servlet-class>
		<init-param>
			<param-name>ff4jProvider</param-name>
			<param-value>${your-implementation-of-FF4JProvider-className}</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>
```
If you want the old override the version of dependency ff4j-web with the version 1.5 (and not 1.5.1 with a bug). I will fixe the old one with 1.5.2 may be this week, sorry for the convenience

**Comment by anandxmj** [comment]
HiI read this post in the hope to change the default FF4J Console url to something else. I coded class just like above FF4JWebConfig with @EnableAutoConfiguration to exclude FF4JWebConfiguration (part of FF4J) but it fails with exception below. I need your help to fix

Failed to process import candidates for configuration class [com.mhe.enterprise.identity.config.FF4JWebConfiguration]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'FF4JWebConfiguration' for bean class [org.ff4j.spring.boot.autoconfigure.FF4JWebConfiguration] conflicts with existing, non-compatible bean definition of same name and class <My package there I decleared FF4JWebConfiguration>

**Comment by anandxmj** [comment]
If I change the class name to avoid name conflict it doesn't boot strap my Config class

**Comment by clun** [comment]
SpringBoot will probably load also the other classes one as @ComponentScan is around which lead to conflict you mentioned.

Could you have a look here : 
https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-springboot have see if you can mimic ? It's a basic working sample using the `spring-boot-starter`
