### ISSUE TITLE
Embedded console is not working

### ISSUE THREAD

**Issue by pedrografael** [clun/ff4j#152]
Hi,

I tried to use org.ff4j.web.embedded.ConsoleServlet to map the console, but I got a different page.
I look inside the class and the console doGet() code is commented.
Is there any reason for this?

Thank you!

**Comment by clun** [comment]
The WebConsole is in heavy development (https://github.com/clun/ff4j/issues/118)
The current master is not OK at the moment. Do you use any released version or the trunk ?

**Comment by pedrografael** [comment]
I tried release 1.5.1 and trunk.
I saw the 1.5 code and it is ok. I will use it.
Thank you so much!!
