### ISSUE TITLE
Performance issue when upgrading to 1.5.1

### ISSUE THREAD

**Issue by damienbeaufils** [clun/ff4j#155]
Hello,

We use FF4J on our front website to check if features are enabled or not. Features status are just read  (i.e. no update) from database using the `FeatureStoreSpringJdbc`.
We have Gatling test performance running after each build, and we detect a performance regression when upgrading from FF4J 1.5 to 1.5.1.

Our Gatling performance test specs : 100 users, going to a single page (the home page for example) 10 times per sec. So we have a total of 60000 requests.
Our results:
- Response time with FF4J 1.5 => mean:287ms, 95th pct:464ms
- Response time with FF4J 1.5.1 => mean:1693ms, 95th pct:5168ms

So beetween 1.5 and 1.5.1, we noticed a 5-10x longer response time.
We did'nt dig yet to find what is causing this performance regression. Maybe you already have a clue?

**Comment by clun** [comment]
Hi,
I was "off" for 2 weeks. Thank you for performing performance tests, very useful for everyone. I think i identifed the problem, it's related to #129. I added a `synchronized` keyword to `check()` method. Will check if I can do better.

**Comment by clun** [comment]
Synchronized will be removed (that won't solve race condition in redis concurrency problem and slow down everything).

**Comment by clun** [comment]
Synchronized are removed, ready for 1.5.2, should fine some solution for redis PB

**Comment by damienbeaufils** [comment]
Thanks. I will run performance tests again when the new FF4J version will be released.
