### ISSUE TITLE
FF4jExceptionHandler is capturing all exceptions

### ISSUE THREAD

**Issue by fernandoteixeira** [clun/ff4j#158]
Hello,

We are using the ff4j-spring-boot-web-api on version 1.5.
The exception handler (FF4jExceptionHandler.java) is capturing all exceptions thrown by our application.
My suggestion is to add the package in ControllerAdvice annotation. What do you think?

Thanks.

**Comment by paul58914080** [comment]
@fernandoteixeira I agree with your suggestion. I guess its happening with IllegalArgumentException. I will add the basePackages to avoid this.

**Comment by fernandoteixeira** [comment]
@paul58914080 Exactly. Its happening with IllegalArgumentException.

Thanks.

**Comment by paul58914080** [comment]
Fixed with https://github.com/clun/ff4j/commit/498bbe832ba054f707e4847ca1350fa568cdf3f1

**Comment by fernandoteixeira** [comment]
@paul58914080 Thanks! We will update to 1.6 when release.
