### ISSUE TITLE
Can I have multiple features for a service?

### ISSUE THREAD

**Issue by LucasHCruz** [clun/ff4j#167]
I'm using Spring so I have `@Flip(name = "name", alterBean = "beanName")`.

Can I have multiple alterBeans* and activate then through feature toggle?

*like:

`alterBeans = {"beanName1", "beanName2"}`

**Comment by clun** [comment]
Hi, Unfortunately the "alterBean" attribute of the annotation is not multi-valued. Currently it makes not sense : at runtime the proxy read the annotation and invoke a single alterbean if present, then returns the value to the caller.

May I help you if I understand which behaviour do you want to implement. 

If we allow several values  (cardinality 1 -> N)  the proxy will then invoke several implementations for a single method invocation, in that case which method result should be propagated to the caller ?

If something else let me know.

**Comment by LucasHCruz** [comment]
Thanks for the answer!!!

I got it what u said... 

My use case is alter between tests services and at same time have an toggle for turn on/off the service in production.

Like:

```
@Component("OriginalBean")

@Component("OriginalTurnOffBean")

@Component("IntegrationBean")
```

**Comment by clun** [comment]
Ok, you would to have multiple implementations of your methods and choose the target based on the beanName, it make sense. Today it's not that easy because Feature is only ON/OFF. Still i can propose you a workaround. 

**Workaround**:

FF4J handle Features but also Properties. Here I would use a Property because you can change its value at runtime it the web console as well. Here a sample definition in XML but work in all stores:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ff4j xmlns="http://www.ff4j.org/schema/ff4j" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="http://www.ff4j.org/schema/ff4j http://ff4j.org/schema/ff4j-1.4.0.xsd">
	<features>
		<feature uid="testFeature" enable="true" />
	</features>
	<properties>	
		<property name="testProperty" value="OriginalBean">
			<fixedValues>
				<value>OriginalBean</value>
				<value>OriginalTurnOffBean</value>
				<value>IntegrationBean</value>
			</fixedValues>
		</property>		
	</properties>
```

Then you can do that :  
```java
public class DynamicInvoke implements ApplicationContextAware {
    
    public static interface MySampleService { void doSomething(); }
    
    public static class MySampleServiceImpl1 implements MySampleService { 
        public void doSomething() { System.out.println("x"); } 
    }
    public static class MySampleServiceImpl2 implements MySampleService { 
        public void doSomething() { System.out.println("Y"); } 
    }
    
    @Autowired
    private FF4j ff4j;
    
    private ApplicationContext ctx;
    
    public void mySampleMethodsToToggle() {
        // Look in FF4J do get current property value
        String targetBeanName = ff4j.getProperty("testProperty").asString();
        // Use this value to pick correct target bean 
        MySampleService s = (MySampleService) ctx.getBean(targetBeanName);
        s.doSomething();        
    }

    @Override
    public void setApplicationContext(ApplicationContext appCtx) throws BeansException {
        ctx = appCtx;
    }
}
```
In v2 I will definitively provide a dedicated annotation to leverage on property value

```java
@FF4JDynamicallyInvoke("targetPropertyUidCodingForTheTargetBean");
```

**Comment by LucasHCruz** [comment]
Got it!!! Thank you very much and congratz for the project!!!!
