### ISSUE TITLE
FeatureStoreMongoDB receives DBCollection but can receive MongoCollection

### ISSUE THREAD

**Issue by LucasHCruz** [clun/ff4j#171]
Hi... I'm using new FeatureStoreMongoDB(DBcollection);

But DBCollection is deprecated...

http://stackoverflow.com/questions/29364787/mongocollection-versus-dbcollection-java

Can I pass MongoCollection in some way?

**Comment by clun** [comment]
Hello,

Or course you can :)

if you use the MongoV3+ database please use the dependency ff4j-Store-Mongodb-v3

https://mvnrepository.com/artifact/org.ff4j/ff4j-store-mongodb-v3

As the API is not backward compatible we had to create 2 different module.

I will add more info once in front my desktop. 

Cedrick
