### ISSUE TITLE
logback.xml should not be present in jar

### ISSUE THREAD

**Issue by Treydone** [clun/ff4j#173]
A logback.xml file is present in the jar ff4j-web and generates conflicts with the logback.xml provided by our applications. The logging configuration should be defined by the user. Is it possible to remove it?

**Comment by clun** [comment]
File has been moved to src/test/resources

**Comment by Treydone** [comment]
Great! Happy to see these issues being fixed! When will you release the new version containing these fixes?

**Comment by clun** [comment]
It should be next week, maybe 22th a security vulnerability to fix before.

**Comment by Treydone** [comment]
Ok thanks
