### ISSUE TITLE
Content-Type is not set for html page

### ISSUE THREAD

**Issue by Treydone** [clun/ff4j#175]
HTML pages are not well interpreted in the browser since they don't have a correct content-type defined: the header "content-type" is not defined at "text/html"

**Comment by clun** [comment]
Shoud be ok, in the master at least, 
https://github.com/clun/ff4j/blob/master/ff4j-web/src/main/java/org/ff4j/web/FF4jDispatcherServlet.java#L61)

Do not tested yet.

**Comment by clun** [comment]
Tested on Edge, Chrome, Firefox.

**Comment by Treydone** [comment]
Thanks!

**Comment by kutzi** [comment]
Can we have a 1.6.1 release with it?
Because the Console, as it is, is not usable for us.

**Comment by clun** [comment]
Released this morning
