### ISSUE TITLE
way to use own created tables in RDBMS ?

### ISSUE THREAD

**Issue by rck935** [clun/ff4j#178]
As per the data model shown for RDBMS it looks, developer does not have the flexibility to add their own table to database and use them.
Please let us know, more information around it with an example (fyi, am using simple jdbc not spring jdbc).
Thanks!
I see and some spring related hints here, (https://github.com/clun/ff4j/blob/master/ff4j-store-springjdbc/src/test/resources/applicationContext-jdbc-test.xml)

**Comment by clun** [comment]
Hi,

FF4J 1.x required 5 tables to work properly: Features, Roles, Properties, Audit, CustomProperties as proposed here : https://github.com/clun/ff4j/blob/master/ff4j-core/src/main/resources/schema-ddl.sql

As you see the tables are prefixed by "FF4J_" but you can totally change this prefix and add suffix as shown here : https://github.com/clun/ff4j/blob/master/ff4j-core/src/test/resources/ddl-prefix-schema.sql
 (and here : https://github.com/clun/ff4j/blob/master/ff4j-core/src/test/java/org/ff4j/test/store/JdbcFeatureStorePrefixTest.java)

```java
JdbcFeatureStore jdbcStore = new JdbcFeatureStore();
jdbcStore.setQueryBuilder(new JdbcQueryBuilder("T_FF4J_", "_01"));
jdbcStore.setDataSource(db);
```
Now, you can add any others table in the same DBn why do you think we can't ? By default, in the Unit Test and DDL i create only the tables for ff4J but you can add your own.

**Comment by rck935** [comment]
@clun thanks for the inputs. It cleared some of my thoughts.
If we add our own table/columns, how exactly it will be reflected on console ? do we need to modify something on the console project code or it will be taken care automatically?

**Comment by clun** [comment]
If you add some tables or colums in the tables they won't appear at al in the console but the console won't failed. The screen of the console are not really dynamic and introspecting database schema (it's not phpMyAdmin).

To perform CRUD operation on any tables through web (it"s named Scaffhoding)  i could recommend JHipster. 

Regards.

**Comment by clun** [comment]
Can i close the ticket @rck935 ?

**Comment by rck935** [comment]
still working on it, so for now am good.
Thanks for the info.
