### ISSUE TITLE
Relationship between feature and properties doesn't work

### ISSUE THREAD

**Issue by tonybo2006** [clun/ff4j#179]
when I  add properties to specific feature from web console. it seems the relationship wasn't created.

**Comment by clun** [comment]
Hi

Could you please validate
- the version number (1.6+) 
- the browser you used.
- you déclared the servlet in web.xml or spring boot/annotations

In order for me to reproduce. 
Will work on it quickly.

**Comment by tonybo2006** [comment]
version number is 1.6.
chrome 54.0.2840.99
declared the servlet with spring boot annotations.

thanks.

**Comment by clun** [comment]
[Following] - Reproduced Bug. 

As you said the property is created but not associated to the feature.
![tonyo](https://cloud.githubusercontent.com/assets/726536/22142669/7069db90-def7-11e6-8db2-8781715e792e.png)
![docu](https://cloud.githubusercontent.com/assets/726536/22142670/71d4dbba-def7-11e6-9055-b4740045d26c.png)

**Comment by clun** [comment]
Fixed:https://github.com/clun/ff4j/commit/70019a390a81d1a9312479a54e13125f1be75a34

**Comment by clun** [comment]
Part of 1.6.2, available on central
