### ISSUE TITLE
Add a confirmation dialog before deleting a feature flag

### ISSUE THREAD

**Issue by thewarpaint** [clun/ff4j#182]
On live systems feature flags can be critical and currently if you delete the wrong flag by mistake there is no going back.

**Comment by clun** [comment]
Totally Agree ! It was on high priority, let's planned it

**Comment by clun** [comment]
Fixed with https://github.com/clun/ff4j/commit/dd84d9d52bcdef832f0763ddc38cd5759edb7655 
(lol note for later : using "Fix..." as comment in git push automatically

![del](https://cloud.githubusercontent.com/assets/726536/22161100/2baf337c-df49-11e6-95f1-ed06554804e5.png)
close the issue.

**Comment by clun** [comment]
Part of 1.6.2, available on central
