### ISSUE TITLE
Question - Documentations CustomProperties + RESTAPI + Thymelead

### ISSUE THREAD

**Issue by CoolSuplex** [clun/ff4j#183]
Hello Team,
Can anyone point to some resource/ example on how we can utilize the custom properties table present on FF4J.
I see we can add properties as below (present on WIKI) but how/what purpose they are for ?
// Custom properties
Feature f4 = new Feature("f4");
f4.addProperty(new PropertyString("p1", "v1"));
f4.addProperty(new PropertyDouble("pie", Math.PI));
f4.addProperty(new PropertyInt("myAge", 12));

-- Feature Internal Custom Properties
CREATE TABLE FF4J_CUSTOM_PROPERTIES (
  "PROPERTY_ID"  VARCHAR(100) NOT NULL,
  "CLAZZ" 		 VARCHAR(255) NOT NULL,
  "CURRENTVALUE" VARCHAR(255),
  "FIXEDVALUES"	 VARCHAR(1000),
  "DESCRIPTION"	 VARCHAR(1000),
  "FEAT_UID"     VARCHAR(100) REFERENCES FF4J_FEATURES("FEAT_UID"),
  PRIMARY KEY("PROPERTY_ID", "FEAT_UID")
);

**Comment by clun** [comment]
I saw 2 main use cases for the custom properties.

**First**, and the reason why it has been asked by users, it is to implement **Flipping Strategy Logic based on values in custom properties**. This way some features will be flipped and not others. Like here

```java
public class TestCustomProperties {
  
  public class AwsRegionFlippingStrategy extends AbstractFlipStrategy {
    
    private FeatureStore fs;
    
    public AwsRegionFlippingStrategy(FeatureStore fStore) {
      fs = fStore;
    }
    
    /** {@inheritDoc} */
    @Override
    public boolean evaluate(String featureName, FeatureStore store, FlippingExecutionContext executionContext) {
      Map < String, Property<?>> customProperties = fs.read(featureName).getCustomProperties();
      if (customProperties.containsKey("awsRegion")) {
        List< String > grantedRegions =  Arrays.asList(customProperties.get("awsRegion").asString().split(","));
        return grantedRegions.contains(AwsUtils.getCurrentAwsRegion());
      }
      return false;
    }
  }
  
  @Test
  public void testFlippingWithCustomProperty() {  
    FF4j ff4j = new FF4j();
    Feature cacheAndwers = new Feature("cacheAnswer", true);
    cacheAndwers.setFlippingStrategy(new AwsRegionFlippingStrategy(ff4j.getFeatureStore()));
    cacheAndwers.addProperty(PropertyFactory.createProperty("awsRegion", "eu-wst1,us-east1"));
    ff4j.createFeature(cacheAndwers);
    if (ff4j.check("cacheAnswer")) {
      // True only is some AWS Region ==> Flippinf based on Property of a feature
      // [...]
    }
    
    // Note: you can override the flipping strategy during you test
    if (ff4j.checkOveridingStrategy("cacheAnswer", new WhiteListStrategy("10.0.0.*"))) {
       // [..] 
    }
  }
}
```
**Second**, is to create **properties associated** to the feature, if you remove the feature you remove all related properties at one shot

```java
 DataSource fallBackDataSource = null;
    
    @Test
    public void testCustomerProperties2() {    
        FF4j ff4j = new FF4j();
        Feature fallbackDatabase = new Feature("fallbackDb", true);
        fallbackDatabase.addProperty(new PropertyString("driverClassName", "com.mysql.JdbcDriver"));
        fallbackDatabase.addProperty(new PropertyString("url", "localhost:3306"));
        fallbackDatabase.addProperty(new PropertyString("userName", "root"));
        fallbackDatabase.addProperty(new PropertyString("password", "sa"));
        
        DataSource fallBackDataSource = null;
        if (ff4j.check("fallbackDb")) {
            if (fallBackDataSource == null) {
                if (fallBackDataSource == null) {
                    Map < String, Property<?>> cp  = ff4j.getFeature("fallbackDb").getCustomProperties();
                    BasicDataSource bds = new BasicDataSource();
                    bds.setDriverClassName(cp.get("driverClassName").asString());
                    bds.setUrl(cp.get("url").asString());
                    fallBackDataSource = bds;
                }
            }
            // Work with datasource
        }    
        
    }
```

**Comment by AshutoshKumar2513** [comment]
@clun thanks for the info.
please point us to documentation/example for REST API which allow any clients like javascript
(link on the home page looks broken)

**Comment by clun** [comment]
Yes, the documentation is still not the best today

Here you get some informations:
https://github.com/clun/ff4j/issues/128

The sample project running the API documentation is here
https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-web-api

**Comment by AshutoshKumar2513** [comment]
@clun super cool, API doc link were helpful, will wait for your final version of it.

Here is my understanding as per the documentation about the existing strategy.
The existing strategies can be used as is, as they are checked in ff4j-core already.
So, if I add a strategy as **org.ff4j.strategy.ReleaseDateFlipStrategy{releaseDate=2017-02-07-20:00}** from my console to one of the feature (backend uses a RDS datastore), so after this date/time, this feature will be flipped automatically?
but it's not happening :(
(FYI, I am running on version 1.3.5)

**Comment by AshutoshKumar2513** [comment]
@clun please provide some documentation. link on TagLib and Thymeleaf integration as well.

**Comment by clun** [comment]
REST documentation is now available on http://ff4j.org/rest-api

**Comment by clun** [comment]
Bug update in documentation, we can consider this issue closed... please.
https://github.com/clun/ff4j/wiki/Web-Concepts#securing-accesses-to-api
