### ISSUE TITLE
FeatureAdvisor wraps exceptions thrown by the proxy target

### ISSUE THREAD

**Issue by berryvanginkel** [clun/ff4j#184]
We are using the @Flip annotation to switch implementations depending on the feature enabled/disabled state. Those implementation might throw an exception and those should handled upstream. 
In method FeatureAdvisor#invokeAlterBean from ff4j-aop, any exception from the target object is wrapped  in a IllegalArgumentException.
We just want our original exception to be rethrown at this point.

Note that this issue has already been reported before in #103 in version 1.5.1 but this solution has been removed from version >1.6. 
Was there any reason for that? 
Also with that solution a property FF4j#alterBeanThrowInvocationTargetException has been introduced which is not present in the 1.6 version anymore and thus breaks compatibility

**Comment by clun** [comment]
Hi,

No particular reason. It's a regression. We had to perform some simplifications to make possible the annotation of CGLIB enhanced classes and remove the patch. 

I put everything back as expected.

**Comment by clun** [comment]
Part of 1.6.2, available on central

**Comment by berryvanginkel** [comment]
Sorry for my late response, but thanks for your very fast fix and release!!
