### ISSUE TITLE
Strategy not working as expected (tried ReleaseDate)

### ISSUE THREAD

**Issue by CoolSuplex** [clun/ff4j#185]
@clun @All,

Here is my observation (/per the documentation) built in existing strategies :
The existing strategies can be used as is, as they are checked in ff4j-core already e.g. ReleaseDate
So, if I attach a strategy as org.ff4j.strategy.ReleaseDateFlipStrategy{releaseDate=2017-02-07-20:00} from my admin console to one of the feature (backend uses a RDS datastore), so after this date/time, this feature will be flipped automatically?
So, flipping on strategy is not happening when added for a NEW feature and neither if we are attaching a strategy to an existing feature (i.e. edit a feature and attach)

(FYI, I am running on version 1.3.5)

Any hints are highly appreciated.

**Comment by clun** [comment]
Hi,

`FlippingStrategy` are only predicates to implement your own behaviour and evaluate if a Feature should be considered as Flipped or not. They will be evaluate if and only if the feature is already enabled, It won't change the status enable/disable by itself.

The algorithm is the following : 
![fig-01-businessrules-flowchart](https://cloud.githubusercontent.com/assets/726536/22857938/711fc32c-f0b0-11e6-9d9d-c3c181c22df8.png)

Please consider the following code:
```java
public class CoolSuplexTest {

    @Test
    public void sampleFlippingStrategy() {
        // Given
        //default, in memory and empty.
        FF4j ff4j  = new FF4j();
        Feature f1 = new Feature("f1", true);
        ff4j.getFeatureStore().create(f1);
        //The feature  is enabled, no flipping strategy
        Assert.assertTrue(ff4j.check("f1"));
        
        // Let's add a flipping strategy (yyyy-MM-dd-HH:mm)
        f1.setFlippingStrategy(new ReleaseDateFlipStrategy("2017-03-01-00:00"));
        ff4j.getFeatureStore().update(f1);
        // Even is feature is enabledn as strategy is false...
        Assert.assertFalse(ff4j.check("f1"));
    }
}
```

**Comment by clun** [comment]
Please note, I updated the wiki 
https://github.com/clun/ff4j/wiki/Core-Concepts#flipping-strategy

Will do the same for taglib and/or thymeleaf

**Comment by clun** [comment]
May i close this question ?
