### ISSUE TITLE
EhCache toggle flip - how to persist to database?

### ISSUE THREAD

**Issue by alexjascott** [clun/ff4j#189]
I am trying to write a unit test to test that disabling a Feature updates the database record.

I'm using FF4jCacheProxy, but the database does not seem to get updated after I disable. How do I force a flush/eviction? I assumed that Feature.Disable() should perform an evict and then a write?

My current FF4J instantiation code;
`

             FF4j ff4j = new FF4j();
             FeatureStore fStore = new FeatureStoreSpringJdbc(dataSource);
             PropertyStore pStore = new PropertyStoreSpringJdbc(dataSource);

            FeatureCacheProviderEhCache ff4jEhCacheProvider = new FeatureCacheProviderEhCache();
            ff4jEhCacheProvider.setCacheManager(cacheManager);
            ff4jEhCacheProvider.setCacheConfiguration(cacheManager.getConfiguration());
            ff4jEhCacheProvider.setCacheFeatures(cacheManager.getCache("ff4j"));
            ff4jEhCacheProvider.setCacheProperties(cacheManager.getCache("ff4j"));
            logger.info("#### cache names: " + Arrays.asList(cacheManager.getCacheNames()));
            logger.info("#### active cache: " + cacheManager.getActiveConfigurationText());

            FF4jCacheProxy cacheProxy = new FF4jCacheProxy(fStore, pStore, ff4jEhCacheProvider);
            ff4j.setFeatureStore(cacheProxy);
            ff4j.setPropertiesStore(cacheProxy);
            ff4j.audit(false);
            ff4j.autoCreate(false); // automatically create null features on check, rather than throw missing exception
            ff4j.createSchema();

            return ff4j;`

**Comment by alexjascott** [comment]
Okay I have found the solution.

Instead of using Feature.toggle() or Feature.disable() you have have call FF4J.disable(FEATURE_ID).

**Comment by clun** [comment]
That's right. There is no "hook" to the bean and updating the bean won't work.

You should (always) start by ff4j.doSomething().

So here : 
```java
// Toggle Off if exist, create the feature is not exist
ff4j.autoCreate().disable("myFeature");
        
// Toggle Off if exist, FeatureNotFoundOtherwiser
ff4j.getFeatureStore().disable("myFeature");
```

Enjoy
