### ISSUE TITLE
DB2 auto create table error

### ISSUE THREAD

**Issue by alexjascott** [clun/ff4j#190]
DB2 dialect issue;

`
CREATE TABLE FF4J_FEATURES( FEAT_UID VARCHAR(100), ENABLE INTEGER NOT NULL, 
DESCRIPTION VARCHAR(1000), STRATEGY VARCHAR(1000), EXPRESSION  VARCHAR(255), 
GROUPNAME   VARCHAR(100), PRIMARY KEY(FEAT_UID));
`

Results in DB2 error;
`
DB2 SQL Error: SQLCODE=-542, SQLSTATE=42831, SQLERRMC=FEAT_UID, DRIVER=3.50.152
`

This is because DB2 insists primary keys are specified "not null".

Is there anyway I can override or specify a SQL dialect?

**Comment by clun** [comment]
Hello, no so far there is not element to override the SQL. 

In v2 FF4j generate the DDL through featureStore.createSchema() but not release yet.

Today the DDL provided (https://github.com/clun/ff4j/blob/master/ff4j-core/src/main/resources/schema-ddl.sql) works for at least Mysql, PostGresSQL. 

Feel free to adapt and provide the file for DB2 i will integrate the pull request.

**Comment by alexjascott** [comment]
Once I have the db event logging working I'll get back to you with my schema.

**Comment by alexjascott** [comment]
This is my current schema+tables script;

'
create schema CONFIGURATION;

CREATE TABLE CONFIGURATION.FEATURES(
 FEAT_UID VARCHAR(100) NOT NULL,
 ENABLE INTEGER NOT NULL,
 DESCRIPTION VARCHAR(1000),
 STRATEGY VARCHAR(1000),
 EXPRESSION VARCHAR(255),
 GROUPNAME VARCHAR(100),
 PRIMARY KEY(FEAT_UID)
);

CREATE TABLE CONFIGURATION.PROPERTIES (
  "PROPERTY_ID"  VARCHAR(100) NOT NULL,
  "CLAZZ"        VARCHAR(255) NOT NULL,
  "CURRENTVALUE" VARCHAR(255),
  "FIXEDVALUES"  VARCHAR(1000),
  "DESCRIPTION"  VARCHAR(1000),
  "FEAT_UID"     VARCHAR(100) REFERENCES CONFIGURATION.FEATURES("FEAT_UID"),
  PRIMARY KEY("PROPERTY_ID")
);

CREATE TABLE CONFIGURATION.CUSTOM_PROPERTIES (
  "PROPERTY_ID"  VARCHAR(100) NOT NULL,
  "CLAZZ"        VARCHAR(255) NOT NULL,
  "CURRENTVALUE" VARCHAR(255),
  "FIXEDVALUES"  VARCHAR(1000),
  "DESCRIPTION"  VARCHAR(1000),
  "FEAT_UID"     VARCHAR(100) REFERENCES CONFIGURATION.FEATURES("FEAT_UID"),
  PRIMARY KEY("PROPERTY_ID")
);

CREATE TABLE CONFIGURATION.ROLES (
  "FEAT_UID"     VARCHAR(100) NOT NULL REFERENCES CONFIGURATION.FEATURES("FEAT_UID"),
  "ROLE_NAME"    VARCHAR(100) NOT NULL,
  PRIMARY KEY("FEAT_UID", "ROLE_NAME")
);

CREATE TABLE CONFIGURATION.AUDIT (
  "EVT_UUID" 	 VARCHAR(40)  NOT NULL,
  "EVT_TIME" 	 TIMESTAMP 	  NOT NULL,
  "EVT_TYPE" 	 VARCHAR(30)  NOT NULL,
  "EVT_NAME" 	 VARCHAR(100)  NOT NULL,
  "EVT_ACTION" 	 VARCHAR(30)  NOT NULL,
  "EVT_HOSTNAME" VARCHAR(100)  NOT NULL,
  "EVT_SOURCE" 	 VARCHAR(30)  NOT NULL,
  "EVT_DURATION" INTEGER,
  "EVT_USER" 	 VARCHAR(30),
  "EVT_VALUE" 	 VARCHAR(100),
  "EVT_KEYS" 	 VARCHAR(255),
  PRIMARY KEY("EVT_UUID", "EVT_TIME")
);
'

**Comment by clun** [comment]
ok, will create schema-db2.ddl in src/main/resources of ff4j-core

**Comment by clun** [comment]
Part of 1.6.3
