### ISSUE TITLE
FF4J Console not getting resources/images

### ISSUE THREAD

**Issue by alexjascott** [clun/ff4j#191]
The Root page (http://localhost:9082/ff4j-console) does not get any of the web resources, so looks very bad. 

If I go in via /home then it all looks fine. So I assume its a trivial issue.

My web.xml settings are as per the instructions;

`
    <servlet>
        <servlet-name>ff4j-console</servlet-name>
        <servlet-class>org.ff4j.web.FF4jDispatcherServlet</servlet-class>
        <init-param>
            <param-name>ff4jProvider</param-name>
            <param-value>com.myCompany.config.FF4JProvider</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>ff4j-console</servlet-name>
        <url-pattern>/ff4j-console/*</url-pattern>
    </servlet-mapping>
`

**Comment by clun** [comment]
Héhé 

Please try `http://localhost:9082/ff4j-console/`  (with the '/' at the end of the URL if I look at your servlet declaration)
