### ISSUE TITLE
JDBC Event Repo = no audit records

### ISSUE THREAD

**Issue by alexjascott** [clun/ff4j#192]
The audits and graphs work fine using the default inmemory event repo.

But trying to get the JDBC event repo working results in no graphs or audits via the web console, although it DOES seem to work in my unit tests!

My init code;

`

            JdbcQueryBuilder queryBuilder = new JdbcQueryBuilder(SCHEMA_NAME + ".", "");

            FeatureStoreSpringJdbc fStore = new FeatureStoreSpringJdbc();
            fStore.setQueryBuilder(queryBuilder);
            fStore.setDataSource(dataSource);
            PropertyStoreSpringJdbc pStore = new PropertyStoreSpringJdbc();
            pStore.setQueryBuilder(queryBuilder);
            pStore.setDataSource(dataSource);

            FeatureCacheProviderEhCache ff4jEhCacheProvider = new FeatureCacheProviderEhCache();
            ff4jEhCacheProvider.setCacheFeatures(cacheManager.getCache(CACHE_NAME));
            ff4jEhCacheProvider.setCacheProperties(cacheManager.getCache(CACHE_NAME));
            logger.debug("cache names: " + Arrays.asList(cacheManager.getCacheNames()));
            logger.debug("active cache: " + cacheManager.getActiveConfigurationText());
            FF4jCacheProxy cacheProxy = new FF4jCacheProxy(fStore, pStore, ff4jEhCacheProvider);

            JdbcEventRepository eventRepo = new org.ff4j.audit.repository.JdbcEventRepository(dataSource);
            eventRepo.setQueryBuilder(queryBuilder);

            FF4j ff4j = new FF4j();
            ff4j.setFeatureStore(cacheProxy);
            ff4j.setPropertiesStore(cacheProxy);
            ff4j.setEventRepository(eventRepo);
            ff4j.autoCreate(false); // automatically create null features on check, rather than throw missing exception
            ff4j.audit(true);
            //ff4j.createSchema(); // doesnt work with DB2

            return ff4j;

`

**Comment by alexjascott** [comment]
I'm seeing some really weird behaviour. It seems to be audit logging for the 1st, 3rd Features; but not the 2nd.

Anything I do with feature 2 does not audit (even creation), but 1 and 3 do.

**Comment by clun** [comment]
Hum strange indeed. 

This MAY due to mix Caching and Auditing :  FF4j accesses cache with contains the expected value && do not contact the target store... and do not audit). But it should work for creation.

The audit(true) will create some AuditProxy.

You can try to enforce auditing like this :

```java
 FF4j ff4j = new FF4j();
 ff4j.setFeatureStore(new FeatureStoreAuditProxy(this, cacheProxy));
 ff4j.setPropertiesStore(new PropertyStoreAuditProxy(this, cacheProxy));
 ff4j.setEventRepository(eventRepo);
 ff4j.autoCreate(false);
```
for creation:
```java
ff4j.getFeatureStore().create(fp);
```
Also try without caching to be sure. 

The events are sent asynchronously using the EventPublisher, if an error occurs, an exception may not be raised...They might also be an issue during insertion of event because it's DB2.

**Comment by alexjascott** [comment]
I am thinking it is to do with the feature.EVENT_UUID column size > AUDIT.EVT_NAME column size.

Currently testing.

**Comment by alexjascott** [comment]
Looks like it was due to the  AUDIT.EVT_NAME size being too small to hold the EVENT_UUID.

Because I'm unable to use the autocreate (DB2) I am manually creating my schema+tables.
