### ISSUE TITLE
Bad ehcache image url

### ISSUE THREAD

**Issue by alexjascott** [clun/ff4j#193]
![bad_ehcache_icon](https://cloud.githubusercontent.com/assets/24542797/23465978/b8b3ecec-fe91-11e6-9732-f800103d31a8.jpg)

The ehcache url looks wrong.

Current (in Home):
static/img/db-EHCACHE.png
Correct (in About): 
static/img/db/db-ehcache.png

**Comment by clun** [comment]
Seems you get you CSS and image Back :) I may close the previous issue.

OK, this is a bug.

**Comment by clun** [comment]
Fixed in 1.6.3
