### ISSUE TITLE
commons-conf url is incorrect

### ISSUE THREAD

**Issue by alexjascott** [clun/ff4j#194]
![image](https://cloud.githubusercontent.com/assets/24542797/23501410/a8a94334-ff2b-11e6-9803-1cde46bcfce8.png)

commons-conf url is incorrect in the About page.

Would also be nice to have a commons-conf example/documentation. I have a legacy app that uses commons-conf, would be nice to be able to plug FF4J into it.

**Comment by clun** [comment]
Ok, Bug, thank you. 

Sample with commons-conf : 
https://github.com/clun/ff4j/tree/master/ff4j-archaius/src/test/java/org/ff4j/commonsconf

Commons-conf is for properties only, same as Archiaus. I may rename to `ff4j-store-archiaus` for next release i think.

**Comment by clun** [comment]
Corrected.

Changing the documentation Accordingly
https://github.com/clun/ff4j/wiki/Store-Technologies#commonsconfiguration

**Comment by clun** [comment]
Fixed in 1.6.3
