### ISSUE TITLE
EventRepository IMG not resolving [similar to CacheManager img issue]

### ISSUE THREAD

**Issue by alexjascott** [clun/ff4j#196]
![image](https://cloud.githubusercontent.com/assets/24542797/23699712/114ce25e-03e8-11e7-9193-cfba9846cc48.png)

img src="static/img/db/db-jdbc.png" style="width:50px"

**Comment by clun** [comment]
this time the image does not exist db-jdbc.png

**Comment by clun** [comment]
... and creating the event repository springjdbc is not that difficult just a matter of time.

**Comment by clun** [comment]
Part of 1.6.3
