### ISSUE TITLE
SetPublisher(customPublisher) will get overwritten by init()

### ISSUE THREAD

**Issue by alexjascott** [clun/ff4j#197]
I'm trying to add an event hook to send an email when someone changes a Feature.

So I've extended EventPublisher, but to get it to work I have to be very careful NOT to allow an init() to happen once set. This is because the init() will overwrite the FF4J eventPublisher instance with the default EventPublisher instead of the one I specify.

**Comment by clun** [comment]
In ff4j v2.x it's better as every audit is done through Observable pattern and you can add your own listener to send mail.

The eventPublisher is now initialized in init() method only if null. (won't be overriden).

**Comment by clun** [comment]
Part of 1.6.3 on central maven
