### ISSUE TITLE
Change property value on feature not working

### ISSUE THREAD

**Issue by LesNovell** [clun/ff4j#199]
Running ff4j 1.6.2.  I'm aware there was a problem with ff4j 1.6.1 creating properties in features, this may be related?

I'm using Redis as a feature store, and when I change a property value on a feature it's not getting persisted as expected.  Instead, the console transitions to the Properties tab.  The new value does not get updated in the feature definition. Here's some screen shots:

![image](https://cloud.githubusercontent.com/assets/10461041/23768374/a3d504ca-04c0-11e7-82b2-a014b9463a22.png)
![image](https://cloud.githubusercontent.com/assets/10461041/23768380/a9e3fa92-04c0-11e7-9de5-71f378174a3f.png)
![image](https://cloud.githubusercontent.com/assets/10461041/23768393/b1844874-04c0-11e7-8290-9931b0a57563.png)

**Comment by clun** [comment]
Yes. It was indeed close to the create property issue , but not the same.  I had to change only the controller.

Please note that "fixedValues" are not supported for properties on features.

**Comment by LesNovell** [comment]
Thanks so much, I noticed you put a Java-style comment into view-modal-properties.html

**Comment by LesNovell** [comment]
I noticed one issue.... When you change the property, it now redirects to the Properties page rather than closing the Property modal and returning to the Feature modal

**Comment by clun** [comment]
Part of 1.6.4 released 2017_05_01
