### ISSUE TITLE
Monitoring data is not available if the feature check is done using Feature/PropertyStoreHttp

### ISSUE THREAD

**Issue by gitsamdev** [clun/ff4j#213]
FF4J version: 1.6.3
When accessing the target feature/property store using ff4j-webapi-jersey1x(FeatureStoreHttp/PropertStoreHttp), feature monitoring data is not displayed.Looks like events are not getting published to the target event store in this case.

**Comment by clun** [comment]
Monitoring is performed by a Proxy on top of the store. It's not related to the underlying store implementation. You should not defined it in the client (using the FeatureStoreHttp) because il will generate a lot of HTTP request just for logging and the is no such thing as EventRepositoryHttp.

So, on the server side (the one expositing the REST API) please do the following : 
```java
FF4j ff4j = new FF4j();     
ff4j.setFeatureStore(/*definition of store using DB of memory*/);
ff4j.setPropertiesStore(/*definition of store using DB of memory*/);
ff4j.setEventRepository(/*definition of store using DB of memory*/);
// Enforcing logging
ff4j.audit(true);
```
And then be sure to reuse this FF4J definition, in the definition of the Jersey1x servlet
```java
/** {@inheritDoc} */
    @Override
    public ApiConfig getApiConfig() {
        if (conf == null) {
            conf = new ApiConfig();
           // Very important !
            conf.setFF4j(Your_FF4j_Instance);
            // <--
            conf.setAuthenticate(false);
            conf.setAutorize(false);
            conf.setDocumentation(true);
            conf.setPort(8080);
            conf.setHost("localhost");
            conf.setWebContext("simple");
            log.info("Returning API Config");
        }
```

**Comment by clun** [comment]
You should tried to upgrade to 1.6+, new Admin UI and backward compatible.

**Comment by clun** [comment]
I will now close the issue, don't hesite do reopen if not clear enough

**Comment by abuinteam** [comment]
Hi Clun

I am using spring boot project (ff4j-sample-springboot-jdbc) deployed as seperate war for admin console and api. All looks good. 

From my web application I am using FeatureStoreHttp and PropertyStoreHttp. It reads the properties from API url and working fine. Only auditing is not working.

Below is my ff4j-sample-springboot-jdbc definition,

@Bean
    public FF4j getFF4j() {
        FF4j ff4j = new FF4j();
        ff4j.setFeatureStore(new FeatureStoreSpringJdbc(dataSource));
        ff4j.setPropertiesStore(new PropertyStoreSpringJdbc(dataSource));
        ff4j.setEventRepository(new EventRepositorySpringJdbc(dataSource));
        ff4j.autoCreate(true);
        ff4j.audit(true);
        return ff4j;
    }

Below is my application side definition

ff4j = new FF4j();           
ff4j.setFeatureStore(new FeatureStoreHttp("http://localhost:9081/api/ff4j"));
ff4j.setPropertiesStore(new PropertyStoreHttp("http://localhost:9081/api/ff4j"));

What am i missing?

**Comment by oemergenc** [comment]
Any hints on this? I am running into the exact same problem? Everythings seems to work, except of monitoring.

**Comment by rivu007** [comment]
We are also running in to the same issue! We are the same setup mentioned by @abuinteam 

Any update would be great!

**Comment by gpr-indevelopment** [comment]
We also have the same issue! We are consuming the flags store via an HTTP client and the monitoring interface is empty.
