### ISSUE TITLE
Can't clear cacheProxy from API when Audit is enable

### ISSUE THREAD

**Issue by jtonnelier** [clun/ff4j#218]
Hi,
First thank you for your awesome tool FF4J! 

I think I found a problem, this is how I instanciate my FF4J Bean (with springboot):
```
FF4j ff4j =  new FF4j();
RedisConnection redisConnection = prepareRedisConnection();
FeatureStoreRedis fsRedis = new FeatureStoreRedis(redisConnection);
PropertyStoreRedis psRedis = new PropertyStoreRedis(redisConnection);
FF4JCacheManager cacheManager = new InMemoryCacheManager();


FF4jCacheProxy proxy = new FF4jCacheProxy(fsRedis, psRedis, cacheManager);

//Enable Supervision
ff4j.audit();

ff4j.setFeatureStore(proxy);
ff4j.setPropertiesStore(proxy);

return ff4j;

```

I want to clear cache, call API with :  /ff4j/store/clearCache 
I got a 404 with this code but if I disable Audit: it's work.

After Some research I think this method from FeatureStoreServices should be modified:

```
public void clearCachedFeatureStore() {
    if(this.ff4j.getFeatureStore() instanceof FF4jCacheProxy) {
      ((FF4jCacheProxy)this.ff4j.getFeatureStore()).getCacheManager().clearFeatures();
    } else {
      throw new FeatureStoreNotCached();
    }
  }
```
To accept FeatureStoreAuditProxy class.

**Comment by clun** [comment]
Nice catch. Indeed if you enable audit then it's a proxy (Audit) of proxy (Cache) but you will throw exception.

Let me come up with something that work with any level of "proxy".

**Comment by jtonnelier** [comment]
Ok no problem 👍

**Comment by clun** [comment]
Part of 1.6.4 released 2017_05_01
