### ISSUE TITLE
Console crashes when strategy is initialized via Spring bean

### ISSUE THREAD

**Issue by arsenaid** [clun/ff4j#22]
ConsoleServlet generates exception on renderPage method when a custom strategy is configured as Spring bean.
Attached is the screenshot.
![2014-10-09_14-33-28](https://cloud.githubusercontent.com/assets/8119170/4584689/16f2ba54-4ffd-11e4-8671-f8ea088b5d22.png)

Here is my config in Spring xml:

    <bean id="ff4j" class="org.ff4j.FF4j" >
        <property name="store" ref="ff4j.store.inmemory" />
    </bean>
    <bean id="ff4j.store.inmemory" class="org.ff4j.store.InMemoryFeatureStore" >
        <constructor-arg type="java.util.Map">
            <map key-type="java.lang.String" value-type="org.ff4j.core.Feature">
                <entry key="myFeature" value-ref="myFeatureRef/>
            </map>
        </constructor-arg>
    </bean>
    <bean id="myFeatureRef class="org.ff4j.core.Feature">
        <constructor-arg name="uid" value="myFeature"/>
        <property name="enable" value="true"/>
        <property name="description" value="Feature description"/>
        <property name="flippingStrategy" ref="myReleaseStrategy"/>
        <property name="group" value="myFeatureGroup"/>
    </bean>
    <bean id="myReleaseStrategy" class="com.mycompany.feature.ReleaseDateFlipStrategy">
        <constructor-arg type="java.lang.String" value="${effectiveDate}"/>
    </bean>

**Comment by clun** [comment]
I escape the '$' caracters during rendition of rows so that next replaceAll do not failed. Will be available for next imminent release.
