### ISSUE TITLE
Bad InMemory CacheManager Image URL

### ISSUE THREAD

**Issue by jtonnelier** [clun/ff4j#221]
Hi!

FF4J Version: 1.6.3

Like issue #193, the URL of InMemory Cache manager image is not correct:

![prtscr capture](https://cloud.githubusercontent.com/assets/4486632/25440393/a1758e5c-2a9f-11e7-8d2e-e7b0b77077f4.png)

Current:
static/img/db/db-in-memory.png

Correct:
static/img/db/db-inmemory.png

**Comment by clun** [comment]
This time a typo in a JavaClass.

https://github.com/clun/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/cache/InMemoryCacheManager.java#L54

**Comment by clun** [comment]
Part of 1.6.4 released 2017_05_01
