### ISSUE TITLE
Sync Store/Cache: check status of store before sync

### ISSUE THREAD

**Issue by jtonnelier** [clun/ff4j#223]
Hi

Today I read the issue #75 and it's exactly what I need in my project.

But I found a little problem in the worker which sync Cache and store: when store is down and polling on, the cache is clear without verification.

After research, _run_ method in _Store2CachePollingWorker_ clear the cache before to check FeatureStore (and PropertyStore too).

```
public void run() {
    Iterator var1;
    if(this.sourceFeatureStore != null) {
      this.cacheManager.clearFeatures();
      var1 = this.sourceFeatureStore.readAll().values().iterator();

      while(var1.hasNext()) {
        Feature p = (Feature)var1.next();
        this.cacheManager.putFeature(p);
      }
    }

    if(this.sourcePropertyStore != null) {
      this.cacheManager.clearProperties();
      var1 = this.sourcePropertyStore.readAllProperties().values().iterator();

      while(var1.hasNext()) {
        Property p1 = (Property)var1.next();
        this.cacheManager.putProperty(p1);
      }
    }

  }
```

I think the cache must not be clear when store is down and this feature of FF4J will be perfect!

**Comment by clun** [comment]
That make sense. 

As there is no  explicit error to qualified that the store is down I can go with a "readAll()" before the clearFeature(), this way it will raise a RuntimeException and exit before invoke the clearFeatures().

**Comment by clun** [comment]
Part of 1.6.4 released today
