### ISSUE TITLE
[jdbcstore] [syntax] - semi colon in sql create statement is a syntax error on oracle

### ISSUE THREAD

**Issue by mabroukb** [clun/ff4j#230]
The semicolon ending the create statement generate an error when running with oracle.

JDBC is intended to execute a statement one at a time. Semicolon in SQL is used as a statement separator.
So the semicolon it is not part of statement syntax for many database including Oracle that I'm using.

for Oracle it is also a syntax error to end a statement with it. 

(remarks : some JDBC drivers will remove it automatically)

Is it possible to remove them ? I can provide a PR but I tested solely on H2 and Oracle.

**Comment by clun** [comment]
PR merged thks !
