### ISSUE TITLE
Upgrade spring & logback

### ISSUE THREAD

**Issue by paul58914080** [clun/ff4j#232]
upgrade to 

| Library         | Version       |  
|-----------------|---------------|
| <ul><li>[x] spring-boot </li></ul>    | 1.5.4.RELEASE | 
| <ul><li>[x] spring </li></ul>            | 4.3.9.RELEASE |
| <ul><li>[x] logback-classic </li></ul> | 1.1.11        |

**Comment by clun** [comment]
1.6.5 is released.
