### ISSUE TITLE
Sample with REST API, Simple JDBC Feature Store and Web Console

### ISSUE THREAD

**Issue by kaisermario** [clun/ff4j#236]
Hello there, 

I am searching for a good library / tool for toggling features in our context.
Therefore I found ff4j and I really like that.

But because of some missing docs, I did not understand all parts of ff4j.
Therefore: Is there a sample project which combines the REST API (with Swagger doc), Simple JDBC Feature Store ( I had only found Spring jdbc) and the admin web console?

Maybe I am blind. 
Sorry for that.

**Comment by clun** [comment]
Hello,

Please have a look to repository ff4j-samples. 

I will check tomorrow if there is exactely what you want, if not I will create it quickly and ping you.

You are right there 2 implementation to work with RDBMS Jdbc core and SpringJdbc you can ping the one you like most.

Côme back to you soon.

**Comment by 1developer1** [comment]
@clun Do you have some news for me? :-)

**Comment by clun** [comment]
Oups I forgot you. Here it is cheers: 
https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-simplejdbc

(`mvn jetty:run` and go `http://localhost:8080/simple`)

**Comment by 1developer1** [comment]
Thank you very much! One last question: How can I open the Swagger API Documentation?

**Comment by clun** [comment]
Swagger documentation is helpful to generate clients in order to consume the API. 
You can also use Swagger-UI to test the API live. Just download the static files from [here ](https://github.com/swagger-api/swagger-ui).  Enter the URL of swagger documentation. You will get something like http://ff4j.org/rest-api/

**Comment by clun** [comment]
Ok, I updated you sample with Swagger UI, enjoy !
