### ISSUE TITLE
'expression=f1 & f2' from web-console will be parsed to 'expression=f1'

### ISSUE THREAD

**Issue by yinjialiang0119** [clun/ff4j#237]
input 'expression=f1 & f2' from web-console will be parsed to 'expression=f1'

see the source code 'org.ff4j.utils.MappingUtil'

public static final Map<String, String> toMap(String strParam) {
        LinkedHashMap<String, String> parameters = new LinkedHashMap<String, String>();
        if (strParam != null) {
           //*********************this line*************************************************
            String[] chunks = strParam.split("\\" + SEPARATOR);
            for (String chunk : chunks) {
                int idxEqual = chunk.indexOf("=");
                if (idxEqual > 0 && idxEqual < chunk.length()) {
                    String paramName = chunk.substring(0, idxEqual);
                    String paramValue = chunk.substring(idxEqual + 1);
                    parameters.put(paramName, paramValue);
                }
            }
        }
        return parameters;
    }

**Comment by clun** [comment]
The error is not spotted in this method but you are right the '&' raise errors. Please use as a workaround `AND` it will work.

**Comment by clun** [comment]
Using InMemoryStore the expression `a & b` is accepted. 

Which you DB ? Tested with 1.6.5

![ff](https://user-images.githubusercontent.com/726536/28117231-d1aecfa8-670c-11e7-8f69-49b8d2203a99.png)

**Comment by clun** [comment]
up ! Do you use the Dispatcher Servlet (available from 1.6.+)

**Comment by clun** [comment]
Can i close this question ?
