### ISSUE TITLE
ff4j_audit table column size issue

### ISSUE THREAD

**Issue by vinodhvp** [clun/ff4j#238]
Hi,

I could see that the FF4J_FEATURES table has the following column definition.
"FEAT_UID"     	VARCHAR(100).

And the ff4j_audit has the following, and the insert/update features fails if the feature name length> 30.
"EVT_NAME" 	 VARCHAR(30)  NOT NULL

Is this an issue with my implementation? I increased the size of the EVT_NAME column in ff4j_audit to 100 and the issue seems fixed.

Thanks
Vinod

**Comment by clun** [comment]
You are right, it's a bug. 

The EVT_NAME should be long enough to have any Feature identifier or Property Name. We reduced in the first place to reduce the space use (there migh be a lot of event out there). I cannot reduce the feature name column without impacting the users.

**Comment by clun** [comment]
Part of 1.7
