### ISSUE TITLE
FlippingStrategy implementations as static nested classes can't be instantiated

### ISSUE THREAD

**Issue by lucjross** [clun/ff4j#239]
I believe ff4j is using `Class#getCanonicalName` where it should be using `Class#getName` for the purpose of instantiating implementations of FlippingStrategy. Not "a.b.c.Enclosing.Nested" but rather, "a.b.c.Enclosing$Nested".

Examples:
* https://github.com/clun/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/strategy/AbstractFlipStrategy.java#L41
* https://github.com/clun/ff4j/blob/master/ff4j-store-mongodb/src/main/java/org/ff4j/store/mongodb/FeatureDBObjectMapper.java#L105

**Comment by clun** [comment]
Hi,

You were. To be honest i was not aware of the distinction between the 2 methods.
https://stackoverflow.com/questions/15202997/what-is-the-difference-between-canonical-name-simple-name-and-class-name-in-jav#15203417

I changed 35 occurences in the framework and re-run the 10k test(s) and still OK.

**Comment by clun** [comment]
Part of 1.7
