### ISSUE TITLE
Dependency Apache Standard Taglibs 1.1.2 - Arbitrary code execution 

### ISSUE THREAD

**Issue by NicoTexas** [clun/ff4j#241]
Apache Standard Taglibs before 1.2.3 allows remote attackers to execute arbitrary code or conduct external XML entity (XXE) attacks via a crafted XSLT extension in a (1) <x:parse> or (2) <x:transform> JSTL XML tag.
See
http://mail-archives.apache.org/mod_mbox/tomcat-taglibs-user/201502.mbox/%3C82207A16-6348-4DEE-877E-F7B87292576A%40apache.org%3E

ff4j-web has a runtime dependency for tag-lib 1.1.2

See main pom.xml
```
    <version.taglib>1.1.2</version.taglib>
```

And ff4j-web/pom.xml
```
    <dependency>
        <groupId>taglibs</groupId>
        <artifactId>standard</artifactId>
        <scope>runtime</scope>
    </dependency>
```

**Comment by clun** [comment]
ok, will try to upgrade to 
```xml
<dependency>
  <groupId>org.apache.taglibs</groupId>
  <artifactId>taglibs-standard</artifactId>
  <version>1.2.5</version>
```

**Comment by clun** [comment]
Correct dependency was 
```xml
<dependency>
            <groupId>org.apache.taglibs</groupId>
            <artifactId>taglibs-standard-impl</artifactId>
            <version>1.2.5</version>
        </dependency>
```

Now fixed and tested 
https://github.com/clun/ff4j/blob/master/ff4j-web/pom.xml#L72-L77

**Comment by clun** [comment]
Part of 1.7
