### ISSUE TITLE
Using Flipping Stategies with REST API 

### ISSUE THREAD

**Issue by kaisermario** [clun/ff4j#244]
Hi there, 

how it is possible to use Flipping Strategies through the provided REST API?
background: we don't want to open a lot of jdbc connections to use FF4J. Instead we want to use the API. 

For example I want to use the flipping strategy: ClientFilter
How can realize to use this strategy with REST API?

Would FF4J check custom properties in the HTTP Request Header?
Or is it possible to use e.g. the ff4j.check() method with a communication via REST API instead of a jdbc connection to the database?

I need really you help....

**Comment by clun** [comment]
Hello,

It is a good idea indeed. You can create a FF4j instance pointing on the REST API only. You will then what I called FeatureStoreHttp and PropertyStoreHttp.

```java
String rootApiUrl = ""http://localhost:9998/ff4j/api";
FF4j ff4j = new FF4j();
ff4j.setFeatureStore(new FeatureStoreHttp(rootApiUrl);
ff4j.setPropertyStore(new PropertyStoreHttp(rootApiUrl);
```

This way when you do ff4j.check("XXX") it will call the API with GET and Strategy if provided in the DB.

Enjoy

**Comment by kaisermario** [comment]
Thank you very much!
