### ISSUE TITLE
Properly securing the web console/rest api ?

### ISSUE THREAD

**Issue by laurentperez** [clun/ff4j#245]
Hi

I've implemented an AuthorizationsManager as per https://github.com/clun/ff4j/wiki/Core-Concepts#permissions-and-security. Tests work as expected.

However, I'm looking for the proper way to secure the web console/apis themselves, and not just the features. Note that I am not using Spring Security or Shiro, due to legacy code (basically, I'm stuck with the servlet/jsp apis under Tomcat, non EE). No iptables, no fw, no nginx or Apache interceptors. I'm already under full HTTPS. Which would be the best option between 

1. writing custom Tomcat Valve or Filter to restrict the console/apis urls
2. extending or forking FF4jDispatcherServlet to inject a bare SecurityManager plus securing the rest api with JJWT 
3. writing a custom Filter (i.e outside of Tomcat)

?

**Comment by clun** [comment]
Hi,

Believe it or not the web console do not use the REST API so far. The reason are (1= the web console existed before the REST API, and (2) I suck at JS. So to secure REST API and console it will be 2 different strategies.

For REST API, something (not standard) is proposed. You can secure with ApiKey of User/Password. In the Api Config object initialization please define expecte ApiKeys.

**Securing accesses to API**
```java
//[..] ff4j definition

ApiConfig apiCfg= new ApiConfig(ff4j);
apiCfg.setAuthenticate(true);
apiCfg.setAutorize(true);

// Sample to Create APIKey
boolean aclAllowRead = true;
boolean aclAllowWrite = true;
Set < String > setofRoles = new HashSet<>();
setofRoles .add("USER");
setofRoles .add("ADMIN");
apiCfg.createApiKey("sampleAPIKey1234567890", aclAllowRead , aclAllowWrite , setofRoles );

// Sample to Create User/password
apiCfg.createUser("myLogin", "myPassword", aclAllowRead , aclAllowWrite , setofRoles );
```
Sample here : https://github.com/clun/ff4j/blob/master/ff4j-webapi-jersey2x/src/test/java/org/ff4j/web/api/test/it/SecuredJersey2Application.java

**Accessing the secured API  :**
```java
FF4j ff4jClient = new FF4j();
ff.setFeatureStore(new FeatureStoreHttp("http://localhost:9998/ff4j", "apiKey"));
```

**Securing WebConsole :**

WebConsole does not provide anything by itself, as it's a single servlet, the authentication must be handle aside. Spring securtiy indeed is a good candidate but any Servlet security mecanism is correct : Filter or security constraints in web.xml are ok to me. If you implement something reusable I would be happy to integrate to the solution.

Please here an architecture consideration. You should not declared the web console in each application. Why not defining a dedicated backend application to handle toggling in a single place like below

![securing ff4j](https://user-images.githubusercontent.com/726536/29212019-bcb5ca8c-7e9c-11e7-8ff5-f31966f02ba5.png)

Should be part of the documentation.... will update accordingly

**Comment by clun** [comment]
Documentation updated : https://github.com/clun/ff4j/wiki/Web-Concepts#securing-accesses-to-api

**Comment by laurentperez** [comment]
Thank you for this very complete answer and the updated documentation :)
