### ISSUE TITLE
Elastic store retrives only 10 feature max even where there are more than 10 features

### ISSUE THREAD

**Issue by paul58914080** [clun/ff4j#249]
The elastic search store is returning only 10 features max (as this is the default implementation of elastic search) when there are more than 10 features defined in the store

**Comment by paul58914080** [comment]
Here is a gist https://gist.github.com/paul58914080/b1e31544b85f25a8abaf7b3971eba918 which could fix

**Comment by clun** [comment]
Thank you Paul, I won't be able to change it for 2 weeks but will do it next

**Comment by paul58914080** [comment]
I will be able to commit this code. But would like someone to review it. Do you think it would be okay if I commit and you or André Blaszczyk would be able to review ?

**Comment by clun** [comment]
Part of 1.7

**Comment by kentilini** [comment]
reproduced again since version 1.8.5
Code was rewritten with the same error =(

**Comment by kentilini** [comment]
@clun I don't have the rights to reopen the issue, should I create a linked one instead?

Fixed bug get back after refactoring (1.8.5 version)
