### ISSUE TITLE
JdbcFeatureStore update() executes commits regardless of autocommit

### ISSUE THREAD

**Issue by Darkstar614** [clun/ff4j#255]
The database that we are using is using auto-commit, and there doesn't seem to be any configuration for JdbcFeatureStore to turn off the "sqlConnection.commit()" in the "update()" method. When it tries to do this, an exception is thrown that auto-commit is turned on.  It seems like create() and delete() seem to toggle auto-commit on and off, but not for update().

The exception is caught and doesn't cause any failures, but it stops the logging capability from the FeaturesController.

Our current workaround is to extend and override the update method to not have the "commit" line.

**Comment by clun** [comment]
PR merged, will align everything today :)thkx

**Comment by clun** [comment]
Part of 1.7
