### ISSUE TITLE
ff4j tablig location is not correct ?

### ISSUE THREAD

**Issue by hlassiege** [clun/ff4j#26]
When using the ff4j taglib, I encountered the following error :

The absolute uri: http://www.ff4j.org/taglibs/ff4j cannot be resolved in either web.xml or the jar files deployed with this application

In documentation it says that the taglib should be discovered if the file is present in META-INF. I'm not sure whether the file should be present in the root of META-INF folder or not. 

For information, I use jetty.

**Comment by clun** [comment]
Hello,

First, to help you I can point you a working sample here (just mvn
jetty:run)
https://github.com/clun/ff4j-extra/tree/master/ff4j-samples/ff4j-sample-web

In the web application I do not have to declare anything in the META-INF
(the TLD il already embedded within ff4j-web.jar).

What a i can tell to you

   - Check dependencies and add if missing the following
   -
   <dependency> <groupId>taglibs</groupId> <artifactId>c</artifactId> <
   version>1.1.1</version> <scope>runtime</scope> <type>tld</type> </
   dependency> <dependency> <groupId>javax.servlet.jsp</groupId> <artifactId
   >jsp-api</artifactId> <version>2.1</version> <scope>provided</scope> </
   dependency>



Ensure that in the JSP you have :
<%@ taglib prefix="ff4j" uri="http://www.ff4j.org/taglibs/ff4j" %>

I already have this mistake in the past during develpment phases and I to
restart jetty (I also work woith jetty most of the time)

Cédrick



2015-01-16 10:15 GMT+01:00 hlassiege <notifications@github.com>:

> When using the ff4j taglib, I encountered the following error :
>
> The absolute uri: http://www.ff4j.org/taglibs/ff4j cannot be resolved in
> either web.xml or the jar files deployed with this application
>
> In documentation it says that the taglib should be discovered if the file
> is present in META-INF. I'm not sure whether the file should be present in
> the root of META-INF folder or not.
>
> For information, I use jetty.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clun/ff4j/issues/26>.
>



-- 

*Cédrick*

*"Try not to become a man of success, but rather try to become a man of
value." (**Albert Einstein)*

**Comment by clun** [comment]
Did you succeed in implementing the taglib, can I close this issue ?
