### ISSUE TITLE
Issue with assets in spring boot

### ISSUE THREAD

**Issue by jackpf** [clun/ff4j#260]
Hi,

I'm attempting to set up ff4j in a fresh project, and the web console cannot load any css/js/images (all 404).
The page is trying to load in from "http://localhost:8080/static/img/flags/flagEnglish.png" whereas the actual location is "http://localhost:8080/ff4j-web-console/static/img/flags/flagEnglish.png".

Is this a configuration issue or a bug?

I have an example project here (run using mvn spring-boot:run): https://github.com/jackpf/demoff4j

Cheers,
Jack

**Comment by paul58914080** [comment]
i think it would be better if you use ff4j-spring-boot-starter which does the same.

Checkout the configuration for web console https://github.com/clun/ff4j/blob/master/ff4j-spring-boot-autoconfigure/src/main/java/org/ff4j/spring/boot/autoconfigure/FF4JWebConfiguration.java

**Comment by jackpf** [comment]
Hi Paul,

I am using the spring boot ff4j starter dependency - see here: https://github.com/jackpf/demoff4j/blob/master/pom.xml#L44

Cheers,
Jack

**Comment by paul58914080** [comment]
End the url with a slash '/' . For example `http://localhost:9082/ff4j-console/`

Probable related issue : https://github.com/clun/ff4j/issues/191

**Comment by paul58914080** [comment]
HI Jack,

Did the above comments work for you ?

**Comment by jackpf** [comment]
Ah adding the slash at the end did work for me, cheers
