### ISSUE TITLE
Couchbase support

### ISSUE THREAD

**Issue by jackpf** [clun/ff4j#265]
Hi,

Is there any plan to add couchbase support for feature store?
Or if not, would it be too difficult to base something off of the mongo store library?

Cheers,
Jack

**Comment by clun** [comment]
Hello,

I would love to support CouchBase, it's the target. Seems that the Java client is straight forward but at the moment I am pretty busy with my "official" Job. Different strategy. I can work on it in the beginning of december.

I can create a skeletton of project with only method to implements if you are interested. It will look like a lot of ff4j-store-cassandra to be honest.

I am not expert on this DB, if you have any tips or idea for the underlying data model it woud be greate as well.

**Comment by jackpf** [comment]
Cheers for the info - I've actually managed to get a basic working store with couchbase based off the cassandra store :)

I'll try and get it into a fully working state with some tests and submit a PR

**Comment by jackpf** [comment]
Hi,

So I've written adapters for couchbase for the property and feature store (not the event store yet).
It's using spring data repositories - however I'm having some difficulty writing integration tests I think due to the versions that are defined in the ff4j parent pom.

Is this something you'd be interested in as a pull request? 

Cheers

**Comment by clun** [comment]
Of course I will ! Thank you so much.

**Comment by jackpf** [comment]
@clun I've created a PR here: https://github.com/clun/ff4j/pull/269

**Comment by clun** [comment]
Well still on refactoring. Would like to test : Cannot install on Windows10, and docker container even hen started do not show anaything on 8091... and you cannot change the port in the Java driver.

Because I used quite a wide set of DB I would like to say this one looks like not yet production ready right ? Still struggle to make it work, the DB, not the store so far...

**Comment by jackpf** [comment]
You should be able to run something like this:
`docker run -d --name db -p 8091-8094:8091-8094 -p 11210:11210 couchbase`
And then access: http://localhost:8091/ui/index.html

(You'll then need to set up the cluster, create a bucket and add 2 views that I've documented in the readme).
I'm not able to test on Windows, but on OSX & Linux this works.

I would say couchbase is definitely production ready - we are using the enterprise version as a document store/cache performing thousands of requests per second.

**Comment by jackpf** [comment]
So it turns out there's currently a bug with CouchbaseMock: https://github.com/couchbase/CouchbaseMock/issues/11

If this gets resolved I should be able to use an embedded database for the tests :)

**Comment by clun** [comment]
I am totally on it. I contacted the Develper Advocate which is french as well (convenient). Problem seems on my station which already used port as even docker can be accessed on localhost:8091.

To my understading is there added value to create several views in a single bucket ?  I did not use it before before thinking about 1 bucket for each type : feature, properties and audit (not the same lifecycle).

Talk to you soon

**Comment by jackpf** [comment]
Ah cool, let me know if you need any more help with it.

So it can be done with one bucket with 2 views, or different buckets can be passed to the stores (like you say, one for feature, one for property etc) and each have a single view - the user can implement it either way they choose

**Comment by clun** [comment]
Could you have a look at the refactoring ? I put the Test as Ignored for now before CouchbaseMock.

- Use 2 buckets because you may have different strategies for properties and features (persistance replication)
- Reuse the FF4J objects, do not introduce extra document
- Simplifications

**Comment by jackpf** [comment]
Just having a look through the refactors - it looks like you've implemented N1QL rather than using the views.
This isn't necessarily a problem, however it will mean that FF4J can't be used on older versions of couchbase where N1QL isn't supported, might be something to bare in mind.
