### ISSUE TITLE
Feature auto create not working using jsp tag library - multiple issues

### ISSUE THREAD

**Issue by abuinteam** [clun/ff4j#268]
Hi,

- **Issue 1**:
When I use the jsp tag library to check for feature it is not auto creating the feature in the feature store
Below is my code for initializing while server startup,

```java
@Override
public void contextInitialized(ServletContextEvent servletContextEvent) {
 LibraryUtil lu;
 try {
  lu = new LibraryUtil();
  lu.retrieve();
  final LibraryMgmtEntity FF4J_API_URL = lu.getPARAM(FF4JConstant.FF4J_API_URL);
  LOGGER.info("Inside contextInitialized for TOCS application");
  final ServletContext servletContext = servletContextEvent.getServletContext();
  ff4j = new FF4j();
  /*ff4j.setFeatureStore(new FeatureStoreHttp("http://localhost:9081/api/ff4j","FF4J","Hello"));
  ff4j.setPropertiesStore(new PropertyStoreHttp("http://localhost:9081/api/ff4j","FF4J","Hello"));*/
  ff4j.setFeatureStore(new FeatureStoreHttp(FF4J_API_URL.getName()));
  ff4j.setPropertiesStore(new PropertyStoreHttp(FF4J_API_URL.getName()));
  ff4j.autoCreate(true);
  ff4j.audit(true);
  servletContext.setAttribute(FF4JConstant.FF4J, ff4j);
  LOGGER.info("contextInitialized for TOCS successful");
} catch (ParserConfigurationException | SAXException | IOException e) {
  LOGGER.debug("");
  e.printStackTrace();
}
```

In my jsp I am using like below

```xml
<ff4j:enable featureid="TOCS_PROJECT1116_TRAFFICAPI">
<li <%=createFromTrafficCSS%>><html:link onclick="exit = false;showLoading()" page="/talentAdviceCreateFromTrafficInterface.do">CREATE FROM TRAFFIC INTERFACE</html:link></li
</ff4j:enable>	
```

- **Issue 2**:
Only in chrome browser feature enable make my application logout due to invalid jsession id. This is not happening in firefox or internet explorer.

```
[WARNING ] Detected JSESSIONID with invalid length; expected length of 23, found 28, setting: 5C329247832837A51BBC7532C77D to null.
```

- **Issue 3:**
I would like to declare my feature inside the constant file and how can I use it in my jsp. I dont want to go for scriplet way of accessing it. Anything like below possible?

```jsp
 <ff4j:enable featureid="${MyConstant.TOCS_PROJECT1116_TRAFFICAPI}">
hello
</ff4j:enable>	
```

**Comment by clun** [comment]
Issue 1, was a but and is fixed
https://github.com/clun/ff4j/blob/master/ff4j-web/src/main/java/org/ff4j/web/taglib/AbstractFeatureTag.java#L84

Issue 2 :
Is it happening here  ? http://sample-env.wgtzd252cy.eu-west-1.elasticbeanstalk.com/ff4j-console/features

**Comment by clun** [comment]
Issue 3 : This is not related to the Tag. You can do it the following way : 
```jsp
<%@ taglib prefix="ff4j" uri="http://www.ff4j.org/taglibs/ff4j" %>
<%@ page import="org.ff4j.sample.MySampleConstants" %>
[...]
<ff4j:enable featureid="<%= MySampleConstants.MY_FEATURE %>">
         HELLO
</ff4j:enable>
```

**Comment by clun** [comment]
Part of 1.7 release

**Comment by abuinteam** [comment]
Hi Clun,

Thank you for fixing this.

After updating 1.7,

Issue 1 is fixed.
Issue 2 is still happening. This could be my application issue. I am checking on it.
Issue 3 is working fine.
