### ISSUE TITLE
Expressions are not correctly rendered in ff4j-web

### ISSUE THREAD

**Issue by kianris** [clun/ff4j#270]
I've created an expression strategy feature through the web interface with expression "A & B".
The value is correct in the database but the web interface only displays up to the ampersand - "A ".

Tested in 1.6.5.

**Comment by clun** [comment]
Hello I did not reproduce.

Could you please test : 
https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-springboot

`mvn spring-boot-run`

I created a feature with an expression and the UI is correct in Both Firefox and Chrome.

**Comment by vmartowicz** [comment]
@clun this is working wirh InMemoryDatabase but not with physical database see #529
