### ISSUE TITLE
FF4jExceptionHandler @Order to low

### ISSUE THREAD

**Issue by Nicomplex** [clun/ff4j#271]
Hello,

I face a problem regarding the `FF4jExceptionHandler`.
The problem is that in my spring application I have several Rest controllers and thus, several ExceptionHandler associated with them.
One of them is a default ExceptionHandler (with `@Order` set to `Ordered.LOWEST_PRECEDENCE`) that trigger on `Exception.class`.
But I noticed that the `FF4jExceptionHandler` class does not have the `@Order` annotation and thus, use the lowest precedence by default.
So for exemple, whenever a `FeatureNotFoundException` is raised, it is caught by my default ExceptionHandler instead of the `FF4jExceptionHandler`.

Just adding the `@Order` annotation to the `FF4jExceptionHandler` class with a value different from `Ordered.LOWEST_PRECEDENCE` resolved the problem.

**Comment by clun** [comment]
Hello,

No issue to add something like if relevant.

```java
@Order(0)
```

Now, does it introduce side-board effect if no other `@Order` annotation is used anywhere. @paul58914080 ?

**Comment by paul58914080** [comment]
@clun that shouldnt be a problem.

**Comment by clun** [comment]
Part of 1.7 release
