### ISSUE TITLE
Problem with spring and feature's uid containing dot '.'

### ISSUE THREAD

**Issue by Nicomplex** [clun/ff4j#272]
We encontered a problem regarding all feature uid that contain a dot '.' (ex: "my.feature.test").
We were using the jersey1x api and all was OK, but when migrating to the spring boot api, the `'check'` endpoint does not behave the same.
For example: with a feature name "my.feature.test", a GET on `"/api/ff4j/check/my.feature.test"` returns a 404 FeatureNotFound error because it is looking for "my.feature" (the ".test" has been truncated by spring).

A workaround for this is to set `PATH_PARAM_UID="{uid:.+}"` in `FeatureConstants` class.

The problem may be present for other `PATH_PARAM_*` constants too, and I am not sure if this fix have side effects. Could you please take a look at this problem?

**Comment by clun** [comment]
I reviewed the spring boot at the moment, 3 issues opened : audit, security.

Will have look this week

**Comment by paul58914080** [comment]
This is linked to https://stackoverflow.com/questions/16332092/spring-mvc-pathvariable-with-dot-is-getting-truncated

**Comment by paul58914080** [comment]
The tried the following configuration which seemed to work

```
@Configuration
public class AllResources extends WebMvcConfigurerAdapter {

    @Override
    public void configurePathMatch(PathMatchConfigurer matcher) {
        matcher.setUseRegisteredSuffixPatternMatch(true);
    }

}
```

**Comment by Nicomplex** [comment]
Indeed, it seems to work for me too.
