### ISSUE TITLE
How to register ff4j-jmx beans with Spring Boot

### ISSUE THREAD

**Issue by callain** [clun/ff4j#274]
Hello, I would like to use ff4j-jmx in my spring boot application.
The wiki is empty on those 2 parts.

I have added the maven dependency but it seems that ff4j jmx beans are not registered automatically by Spring Boot 

Any advice ?

**Comment by callain** [comment]
Okay I found the correct way to do that with Spring.

Simple add this dependency in your pom.xml if you use maven.

```xml 
<dependency>
    <groupId>org.ff4j</groupId>
    <artifactId>ff4j-jmx</artifactId>
</dependency>
```
Create Spring Configuration class, an instance of FF4J and scan org.ff4j.jmx package.

```java
@Configuration
@ComponentScan(basePackages = "org.ff4j.jmx" )
public class FF4JConfiguration {
    
    /**
     * Create and configure FF4J
     */
    @Bean
    public FF4j getFF4j() {
        return new FF4j("ff4j.xml");
    }
}
```

**Comment by clun** [comment]
Yes, correct. Sorry for the delay.

Thank you for the wiki as well !
