### ISSUE TITLE
Web console: ClearCache not working

### ISSUE THREAD

**Issue by cerealk** [clun/ff4j#275]
Hi everyone, 
I have problems in making the button ClearCache working in the web console: it seems that it points to nowhere (also if the response from the servlet is HTTP 200).

Is it the expected behaviour because it has not been implemented yet or I am missing something?

Thank you

**Comment by clun** [comment]
Hello,

Hum, oups,  indeed the controller do not handle this operations. Should be added : 
https://github.com/clun/ff4j/blob/master/ff4j-web/src/main/java/org/ff4j/web/controller/HomeController.java#L113

**Comment by abuinteam** [comment]
Hello Clun,

When this feature can be available?

**Comment by clun** [comment]
Let me that happens for Xmasw Next week for sure I will have plenty of time.

**Comment by abuinteam** [comment]
Hello Clun,

Thank you very much for your response. Happy holidays!!!!

**Comment by clun** [comment]
Part of 1.7.1 just released
