### ISSUE TITLE
Cannot use custom FlipStrategy from other classloader

### ISSUE THREAD

**Issue by cbuehler** [clun/ff4j#284]
I have a [Play1](https://www.playframework.com/documentation/1.4.x/home) application and want to implement a custom FlipStrategy.

Unfortunately, because of the way how Play works, `MappingUtil` has a different classloader than my FlipStrategy. `MappingUtil` has the regular `Launcher$AppClassLoader`, my FlipStrategy has the `ApplicationClassLoader` from Play.
Because of this I get a `ClassNotFoundException` in `MappingUtil.instanceFlippingStrategy`.

Any suggestions for a workaround or a fix?

**Comment by cbuehler** [comment]
Providing the classLoader would perfectly solve my use case.
I made a suggestion in #286.

Using the REST API would not fit my architecture well, because I have a microservice architecture, where multiple services access one central feature store.

**Comment by clun** [comment]
PR merged, will release later today hopefully (Fixing 285 in progress)

**Comment by cbuehler** [comment]
Awesome, thanks a lot for the quick responses.
