### ISSUE TITLE
Having a default configuration when using FeatureStoreMongodb

### ISSUE THREAD

**Issue by hlassiege** [clun/ff4j#29]
Hi,

I'm using FeatureStoreMongodb and I'm wondering if if would be a good idea to be able to pass a filename to initialize with features configuration if features do not exist in database.

Currently, I use a workaround like this : 

```
    @Bean
    public FeatureStore featureStore() {
        MongoCollection ff4j = jongo.getCollection("ff4j");
        FeatureStoreMongoDB storeMongoDB = new FeatureStoreMongoDB(ff4j.getDBCollection());

        InMemoryFeatureStore localStore = new InMemoryFeatureStore("ff4j.xml");
        Map<String, Feature> features = localStore.readAll();

        features.keySet()
                .stream()
                .filter(featureName -> !storeMongoDB.exist(featureName))
                .forEach(featureName -> storeMongoDB.create(features.get(featureName)));

        return storeMongoDB;
    }
```

I divert the original use of InMemoryFeatureStore just to use its parsers. Then I check if features exists in the mongodb store. And if not, I create the feature. 
That's a solution to initialize the application with some features or to add features lately.

Maybe another way of writing that would be 

```
    @Bean
    public FeatureStore featureStore() {
        MongoCollection ff4j = jongo.getCollection("ff4j");
        // all the previous logic managed by FeatureStoreMongoDB ?
        return new FeatureStoreMongoDB(ff4j.getDBCollection(), "ff4j.xml");
    }
```

**Comment by clun** [comment]
Hello,

It's not difficult to implement if you would find it useful. In a firt intention, I should have imported the target XML through dedicated web console. But I think about testing and it's definitely simplier to take an XML as to create each feature through dedicated operations (create(new Feature(...)).

**Comment by clun** [comment]
This behaviour is implemented for all FeatureStore
FeatureStore fff = new FeatureStore([existing-parameters], "ff4j.xml");
or 
fff.importFromXmlConfigurationFile("ff4j.xml")
