### ISSUE TITLE
why using text/plain for CONTENT_TYPE_JS ?

### ISSUE THREAD

**Issue by hlassiege** [clun/ff4j#41]
Hi,

In the embedded console, the js file is served with a content type "text/plain" 
So if I deploy this servlet in an application with spring security, I get the following error when I get to the page : 

Refused to execute script from 'https://localhost:8080/admin/ff4j?rsc=js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Is there any reason to serve the file in "text/plain" instead of "application/javascript" ?

**Comment by clun** [comment]
There were no reason. Please update to 1.3.1 where this bug has been corrected
https://github.com/clun/ff4j/blob/master/ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleServlet.java

**Comment by clun** [comment]
duplication of #31
