### ISSUE TITLE
Cannot map ff4j-1.4.0.xsd to Java classes using xjc

### ISSUE THREAD

**Issue by 1gnition** [clun/ff4j#43]
ff4j-1.4.0.xsd contains two attribute elements with name `value`. When running
`xjc ff4j-1.4.0.xsd`
xjc issues the following error:
`Property "Value" is already defined`

While it's possible using xml bindings file and map `value` to `valueAttribute`, it's a bad solution because further along the way when you unmarshal an ff4j xml with JAXB you'll get:
`Multiple fields representing property "value"`

I suggest changing the `value` attribute names in the xsd to something like `valueAttribute`

**Comment by clun** [comment]
I definitively have to change the XSD. In future versions you will be able to toggle features but also properties. I had to adapt the XML configuration file a little bit. But i try to maintain backward compatibility though.

Here a full sample of new capabilities : 
https://github.com/clun/ff4j/blob/master/ff4j-core/src/test/resources/ff4j-parser-all.xml

**Comment by clun** [comment]
Hi, 

I don't think using XJC, and JAXB in general is the good way to work with ff4j xml file. I used to like it but it really painful to make it evolve. I prefer parse the file in an old low-level DOM way. You should never have to parse it yourself.

To *read* from and ff4J XML file you can use :
 ```java
new FF4J("xmlfile.xml").getFeatureStore().readAll(); 
```

To *generate* an ff4J xml file : 
```java
 Map<String, Feature> features = getFf4j().getFeatureStore().readAll();
 InputStream in = new XmlParser().exportFeatures(features);
```

For information here is the new XSD (1.4) for next releases
![xml-1 4](https://cloud.githubusercontent.com/assets/726536/8398657/052f1d3e-1df8-11e5-87ea-f2ba5b759d10.png)
