### ISSUE TITLE
FF4J.disableGroup()  enable the group instead

### ISSUE THREAD

**Issue by mickeybr** [clun/ff4j#46]
Need to change:
```
    public FF4j disableGroup(String groupName) {
        getFeatureStore().enableGroup(groupName);
        getEventPublisher().publish(groupName, EventType.DISABLE_GROUP);
        return this;
```

To

```
    public FF4j disableGroup(String groupName) {
        getFeatureStore().disableGroup(groupName);
        getEventPublisher().publish(groupName, EventType.DISABLE_GROUP);
        return this;
```

**Comment by clun** [comment]
strange that it pass through unit testing, i got a good code coverage, not enough.

Will be available soon

**Comment by mickeybr** [comment]
I think no one has noticed because the console calls the FeatureStore to enable/disable groups. Only that call does not provide the eventing like FF4J does.

I would have forked and created a PR to fix, but I was not sure how you handle the issues.

 

Thanks,

John Brown

**Comment by clun** [comment]
Correction done, ready for release
