### ISSUE TITLE
How can I deploy the Full Stack Console on a Tomcat server

### ISSUE THREAD

**Issue by Asitha** [clun/ff4j#49]
I'm trying to deploy  [full stack console](http://ff4j.org/images/console-01-homepage.png) on a Tomcat server. I was able to deploy an embedded console on the Tomcat server. But what I need is to deploy the [full stack console](http://ff4j.org/images/console-01-homepage.png). I couldn't find any documentation on this.

Any help on this is much appreciated.

**Comment by clun** [comment]
Hi Asitha,

here there is the code ;
https://github.com/clun/ff4j-extra/tree/master/ff4j-console

You can then mvn jetty:run to test locally and build the war file

The War is available (a standalone jar also) there : 
http://sourceforge.net/projects/ff4j/

Regards

**Comment by clun** [comment]
Please let me know of other element required
