### ISSUE TITLE
FF4j disableGroup method enables instead of disable

### ISSUE THREAD

**Issue by hzariv** [clun/ff4j#50]
See: getFeatureStore().enableGroup(groupName) in the following method. Issue in ff4j-core-1.3.1

  /**
     * Disable group.
     * 
     * @param groupName
     *            target groupeName
     * @return current instance
     */
    public FF4j disableGroup(String groupName) {
        getFeatureStore().enableGroup(groupName);
        getEventPublisher().publish(groupName, EventType.DISABLE_GROUP);
        return this;
    }

**Comment by clun** [comment]
Thank you for the notice. It's now fixed, I will release soon !
