### ISSUE TITLE
Cannot switch off auditing

### ISSUE THREAD

**Issue by aclemons** [clun/ff4j#56]
I could like to completely disable the auditing in ff4j in certain scenarios. Unfortunately EventPublisher is not an interface, so I cannot implement a NoOpEventPublish, but with the new setter for EventPublisher, I could set the EventPublisher to something like:

```
        new EventPublisher() {
            @Override
            public void publish(final Event e) {
                // do nothing
            }
        };
```
It would be nice if org.ff4j.FF4j had a setAuditEnabled(boolean) or something similiar which would cause it to not call getEventPublisher().publish(..) in the first place.

What do you think?

**Comment by clun** [comment]
I agree the auditEnabled flag is really good idea...

**Comment by clun** [comment]
every invocation of the publish is now embedded with the isEnableAudit() test
