### ISSUE TITLE
Improve website

### ISSUE THREAD

**Issue by galan** [clun/ff4j#62]
There are some corrections to be made one the website:
* Link the pdf from github instead of sourceforge
* The images and links of the use-cases do not work correctly

Since it is a static site, I recommend using github to host the site.

**Comment by clun** [comment]
* The link is updated to point to last version of reference guide in github
* Images and links are updated
* Some typo corrections

github could host the site you are right. But to be able to use the org.ff4j package name in maven centrasite a must keep the URL alive. And it's simpler to upload.
