### ISSUE TITLE
Editing feature in embedded console disables feature

### ISSUE THREAD

**Issue by aclemons** [clun/ff4j#66]
If I edit a feature which is currently enabled through the embedded console, the feature status if flipped to false after the update. This is because the console servlet calls:

`org.ff4j.web.embedded.ConsoleOperations.updateFeatureDescription(FF4j, HttpServletRequest)`

which does not read the feature from the store but instead uses:

`Feature fp = new Feature(featureId, false);`

This means the object passed to the feature store for update always has its status set to false. Is this expected behaviour?

**Comment by clun** [comment]
This behaviour is not correct. 

I didn't want to initialize the Feature object with a FeatureStore.read(id) and avoid populating all fields  (could have some side effect - if you want to clean the description for instance).... but I agree some fields must be retrieved and the status is one of us.

```java
Feature old = ff4j.getFeatureStore().read(featureId);
Feature fp = new Feature(featureId, old.isEnable());
```

**Comment by clun** [comment]
Correct and commited
