### ISSUE TITLE
Use JSR 107 JCache for CacheManager

### ISSUE THREAD

**Issue by clun** [clun/ff4j#67]
Become a standard for all cache manager

**Comment by clun** [comment]
done ! tested with HazelCast, JacheRI and EHcache v3

**Comment by ouaibsky** [comment]
Hi Cedric
Nice feature, it's just a shame to release a 1.3.* with this because it broke a lot of things (no more FeatureCacheManager)
Can you tell me up-to wich version this class still available ?

Thx
christophe

**Comment by clun** [comment]
Hello, 

The FeatureCacheManager has been renamed to "FF4JCacheManager" in 1.3.4 because now you can toggle and edit feratures but also any kind of property (PropertyStore). I should have put it 1.4x at least you're right.

Please note that FeatureStore and CacheManager and 2 distinct thing. The first implements the CRUD mechanims and the second is a meant to be used as a proxy of the first. If you choose to work with a FeatureStore already base on distributed cache no need to FF4JCacheAnymore.

**Comment by ouaibsky** [comment]
Hi
Nice, Thx you Cedric
For you information we put in place ff4j in my project based on microservices. it's just a start, and we plan to leverage more and more in the future
If you want a feedback, you know where we are ;)
