### ISSUE TITLE
Fix documentation - JDBC Store

### ISSUE THREAD

**Issue by nakamura** [clun/ff4j#68]
The script to create the tables needed to store the features via JDBC has a problem. The column "FEAT_UID" has different sizes, but they should be the same:

<code>
-- Main Table to store Features
CREATE TABLE FF4J_FEATURES (
  "FEAT_UID"        VARCHAR(100),
...
);

-- Roles to store ACL, FK to main table
CREATE TABLE FF4J_ROLES (
  "FEAT_UID"     VARCHAR(50) REFERENCES FF4J_FEATURES("FEAT_UID"),
...
);
</code>

The column should VARCHAR(100) for both:

<code>
-- Main Table to store Features
CREATE TABLE FF4J_FEATURES (
  "FEAT_UID"        VARCHAR(100),
...
);

-- Roles to store ACL, FK to main table
CREATE TABLE FF4J_ROLES (
  "FEAT_UID"     VARCHAR(100) REFERENCES FF4J_FEATURES("FEAT_UID"),
...
);
</code>

**Comment by clun** [comment]
You are right.

i corrected the discrepancies and also change some length up to 1000 for description for instance.
