### ISSUE TITLE
Fix FeatureCacheProviderRedis

### ISSUE THREAD

**Issue by bhanushe** [clun/ff4j#69]
Currently, the constructor for FeatureCacheProviderRedis accepts 2 parameters but uses defaults while creating new Jedis object. 

    public FeatureCacheProviderRedis(String host, int port) {
        jedis = new Jedis(redisHost, redisport);
    }

Kindly update the constructor to use the parameters.

The method below uses a prefix to search for cache keys. 

    @Override
    public Set<String> listCachedFeatureNames() {
        return jedis.keys(PREFIX_KEY + "*");
    }

I believe the presence of the prefix "PREFIX_KEY" may be an error. The "put" method does not use the prefix to cache the feature. Hence this method returns empty set unless it is backed by a Redis feature store (which is not correct, as in that case it return the actual feature rather than the cached feature)

**Comment by clun** [comment]
Your were right in both cases. 

The constructor is now corrected.

I committed a "new" jcache store which lead to a bit of changes in all caches. (Unfortunately Redis is not yet compliant with JCache). Anyway I kept the prefix everywhere to be able to distinct features and properties.
