### ISSUE TITLE
Javascript issue when editing feature in console

### ISSUE THREAD

**Issue by rtm81** [clun/ff4j#73]
I am testing with ff4j version 1.3.5

When i want to edit a feature i click on the edit button and it looks like this:

![2016-01-12_153536](https://cloud.githubusercontent.com/assets/1322712/12266204/2b667a20-b942-11e5-852c-92e910678195.png)

When i select any Group, Strategy or Permission, then i come to this page.

![2016-01-12_153629](https://cloud.githubusercontent.com/assets/1322712/12266232/577592ea-b942-11e5-801a-47ff90125575.png)

When i click the back button, no change is stored.

My browser is Mozilla Firefox 43.0.4

**Comment by clun** [comment]
I reproduced the issue using the demo application (http://cannys.com/ff4j-demo/ff4j-console) login=password=admin

Seems the javascript code is "opened" as a new page and not interpreted.
javascript:$('#groupName').val('saturn');

**Comment by clun** [comment]
Bug now corrected for all pages, as the test coverage has reached expected level I should be able to release 1.3.6 soon

**Comment by clun** [comment]
Release 1.4 has the update
