### ISSUE TITLE
Missing remote client persistance options to allow for HA

### ISSUE THREAD

**Issue by flyhard** [clun/ff4j#75]
It would be useful to be able to decorate any FeatureStore with caching and persistence.

I need to be able to use a remote client that continues working even if the central server is unavailable. Even if you start the application when the central store is down you should be able to fall back onto the previous value. I am thinking of someything like this:

- If feature flag is in cache and not older than timeout specified - use that.
- If cache expired, try remote.
- If remote timeout (needs to be configurable), trip circuit breaker and try loading from local persistance store.
- If remote answers, put into cache and persist to local storage
- If all fails, use default value

**Comment by clun** [comment]
Actually there is already a caching mechanism. (in a cache-aside pattern).

By declaring a CacheProxy and no the FeatureStore directly. Here is a sample : https://github.com/clun/ff4j-extra/blob/master/ff4j-demo/src/main/resources/applicationContext.xml

If feature flag is in cache and not older than timeout specified - use that.
If cache expired, try remote.
==> [OK]

If remote timeout (needs to be configurable), trip circuit breaker and try loading from local persistance store.
==> Difficult to implement (remote store + cache + localstore)

If remote answers, put into cache and persist to local storage
If all fails, use default value

Still the idea of a backup store is great and could be used for failover and resilience. Il will enhance the Proxy to no handle handle cache but also switch, may I use Hystrix or Ribbon from Netflix to implement this behaviour.

**Comment by flyhard** [comment]
Actually, even better would be if the cache would spawn a background task that fetches all features ever X seconds so that the cache never times out.

**Comment by clun** [comment]
As requested, the `FF4jCacheProxy` could have a thread in background to refill cache from store

```java
   
    @Test
    public void testCacheProxyManagerProperty() throws InterruptedException {
        // When
        FeatureStore  fs = new InMemoryFeatureStore("ff4j.xml");
        PropertyStore ps = new InMemoryPropertyStore("ff4j.xml");
        FF4JCacheManager cm = new InMemoryCacheManager();
        FF4jCacheProxy proxy = new FF4jCacheProxy(fs, ps, cm);
        // Start polling on 100ms basis
        proxy.startPolling(100);
        // Wait for first polling to fill the cache a first time
        Thread.sleep(200);
        
        // When (Remove something)
        fs.delete("AwesomeFeature");
        // Then (Proxy is not yet refresh)
        Assert.assertTrue(proxy.exist("AwesomeFeature"));
        
        // When (wait for cache refresh)
        Thread.sleep(200);
        // Then (also delete in cache si Cache is refreshed)
        Assert.assertFalse(proxy.exist("AwesomeFeature"));
    }
```
