### ISSUE TITLE
Implement Audit trail for Changes to feature flags

### ISSUE THREAD

**Issue by flyhard** [clun/ff4j#76]
We need to have a auditing capability so that we always can trace who did which change.

One way of doing it would be a write through hazelcast to a GIT-repo with the user as committer and/or author.

**Comment by clun** [comment]
There is some Event Publishing capability in order to create some dashboard of feature usage. The change of status could be add to this.

**Comment by clun** [comment]
All operation on stores are now traced and pushed to AUDIT (event Repository). InMemory and JDBC are  available.

I will report this behavior on each store technology soon.
