### ISSUE TITLE
Embedded administration console - check return codes

### ISSUE THREAD

**Issue by aclemons** [clun/ff4j#89]
I've put a tiny servlet filter in front of the embedded admin console to implement a read-only view of the current state. If the user does not have the write role, I am returning a 403 for any write operations  (disable / enable feature, import features, edit features etc).

As a example, if a read-only user tries to disable a feature, a 403 is returned and no changes are done to the feature store, but the UI displays the feature as disabled. Refreshing the page show that the feature is indeed still enabled. It seems the js code does not check the return value of the GET request which disables the request. Would this be possible to implement?

**Comment by clun** [comment]
Done ! (look at the picture). If the servlet will return 403 or 401 HTTP code there will be a dedicated error message and the UI won't change.

![cap](https://cloud.githubusercontent.com/assets/726536/14781289/ebd08e22-0ae1-11e6-918b-08d0060d5272.png)

I changed the $GET by some $AJAX which allow to test return codes

```javascript
    	$.ajax({
    	    type: 'GET',
    	    url: $(location).attr('href') + '?op=disable&uid=' + $(flip).attr('id'),
    	    success: function(data){
    	    	 $('#message').html(data);     
    	    },
    	    statusCode: {
    	    404: function() {
    	    	 $('#message').html("404 An error Occured");
    	    	 
    	    },
    	    403: function() {
    	   		$('#message').html('<div class="alert alert-error" >' +
    	   				'<button type="button" class="close" data-dismiss="alert">&times;</button>' +
    	   				'<span style="font-style:normal;color:#880000;">' +
    	   				'Forbidden </span></div>');
    	   		$(flip).prop('checked', true);
    	   }
    	  }
    	});
```

**Comment by aclemons** [comment]
Looks nice, thanks!
